### ISSUE TITLE
File Upload component

### ISSUE THREAD

**Issue by ghost** [meta-magic/amexio.github.io#10]
Hello, 

Any plan to offer FileUpload component in upcoming release.

Thanks

**Comment by ketan-gote** [comment]
This will get added in next release which is planned for september.

**Comment by nni123** [comment]
Just want to verify if file upload component is included in the new release...

can't find in demo link or source code.

http://www.amexio.org/showcaseapp/v3/index.html#/home

Thanks

**Comment by ketan-gote** [comment]
File upload component is not included in this release (v3.0), We are coming with point release in week which should have it.

**Comment by sagarjadhav968** [comment]
File upload component is available in amexio version v3.0.1
