### ISSUE TITLE
File upload dont work

### ISSUE THREAD

**Issue by baminmru** [meta-magic/amexio.github.io#102]
## I'm submitting a...

<pre><code>
[X ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

control  call http-url,  but  file data not send

## Expected behavior

File data  send to specified http-url

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## Environment
Windows 10
<pre><code>
Angular version: 6.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X ] Firefox version 62
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.11.0  
- Platform:  Windows 

Others:

</code></pre>

See fileupload.component.ts at line 205.
  getFileListData() {
    const formData = new FormData();  // formData always empty !!!

**Comment by rashmithakkar** [comment]
We will check and get back to you soon.

**Comment by rashmithakkar** [comment]
Hi @baminmru ,  We are sorry that it took long to resolve the bug. 
You will find it resolved in v5.4.1 .

Please take update and if you find any more issue please revert us back.
