### ISSUE TITLE
amexio-nav-item not showing amexio-label

### ISSUE THREAD

**Issue by ramesh470** [meta-magic/amexio.github.io#103]
in amexio-nav-item im not able show amexio-label for welcome message on the nav header.

my code:
<amexio-nav [logo]="'assets/images/logo.png'">
    <amexio-nav-item position-right >
        <amexio-label>Hello Mr.XYZ</amexio-label>
    </amexio-nav-item> 
</amexio-nav>

and also im not able to disable textfield in amexio-nav-item 
code:
<amexio-nav [logo]="'assets/images/logo.png'">
    <amexio-nav-item position-right
    [type]="'textfield'"
    [title]="'Enter your name'" [(ngModel)] = "uname" [disabled]="true">
</amexio-nav>

please help me in that.
Thanks in advance.

**Comment by rashmithakkar** [comment]
We will check and get back to you soon...

Thanks

**Comment by rashmithakkar** [comment]
It is possible to add label by using [title] attribute in amexio-nav markup.
Code for reference: 
<amexio-nav [logo]="'assets/images/logo.png'" 
**[title]="'Amexio'"**>
<amexio-nav-item position-right 
[type]="'textfield'"
[title]="'Enter your name'"
[(ngModel)]="uname" >
</amexio-nav-item>
</amexio-nav>

Amexio-nav-item doesnot have disabled property. We will add it to fulfill your requirement and update you once we add that property.

Thanks.

**Comment by ramesh470** [comment]
Thanks for your reply mam,i will check your solution it is satisfied my requirement or not.
my requirement is need to display username in header after login. i will check and let you know.

**Comment by ramesh470** [comment]
hi @rashmithakkar  mam,
can you please help me ,some times dropdown [(ngModel)] values are not working.
i have multiple dropdowns in a page, i will send request to server at that some times values or not working.
ex: if we have grid in our page,i will submit request to the server and get response into the grid. if i click any page in the grid pagination and then again i submit request to the server at this time im not getting any reponse.

my dropdown code:
  <amexio-row >
       <amexio-column [size]="4">
        <amexio-dropdown [(ngModel)]="StateName"
          [place-holder]="'Choose'"
          name="StateName"
          [data]="getStates"
          [data-reader]="'statesdata'"
          [field-label]="'Choose State'"
          [display-field]="'name'"
          [value-field]="'name'"
          (onSingleSelect)="selState($event)">
        </amexio-dropdown>
      </amexio-column>
       <amexio-column [size]="4">
        <amexio-dropdown  [(ngModel)]="DistrictName"
        [place-holder]="'Choose'"
          name="DistrictName"
          [data]="getDists"
          [data-reader]="'districtdata'"
          [field-label]="'Choose District'"
          [display-field]="'name'"
          [value-field]="'name'"
          (onSingleSelect)="selDist($event)">
      </amexio-dropdown>
     </amexio-column>
     <amexio-column [size]="4">
        <amexio-dropdown  [(ngModel)]="CityName"
        [place-holder]="'Choose'"
          name="CityName"
          [data]="getCities"
          [data-reader]="'citiesdata'"
          [field-label]="'Choose City'"
          [display-field]="'name'"
          [value-field]="'name'"
          (onSingleSelect)="selCity($event)">
      </amexio-dropdown>
      </amexio-column>
     </amexio-row>


please help me in that.
thanks in advance.

**Comment by sagarthecook** [comment]
hi @ramesh470  Sorry for the delay on this! 
For model binding checkout below example
 [Example](https://stackblitz.com/github/sagarjadhav968/employee-portal)
Lmk if you run into any more issues.
