### ISSUE TITLE
SA - Amexio-chart-d3 module not found

### ISSUE THREAD

**Issue by arafkarsh** [meta-magic/amexio.github.io#104]
**Sender**: kailaskokate122@gmail.com
**Comment**: I have installed
CLI: npm install amexio-chart-d3 --save 
Also Add in app.module.ts
but not working
there are any required in other files
[Open #28 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-1s6s/p/amexio-api-a0fddca1/28)
**Notes**:
 - (1) ERROR in src/app/app.module.ts(15,37): error TS2307: Cannot find module 'amexio-chart-d3'.

<a href='https://usersnappublic.s3.amazonaws.com/2018-11-05/07-37/bd9cc926-9c3a-444e-a6a6-5d1c14275c8f.png'>![SA - Amexio-chart-d3 module not found](https://usersnappublic.s3.amazonaws.com/2018-11-05/07-37/6deb6d8e-a308-41d5-ba24-a322d2e0833a.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-11-05/07-37/bd9cc926-9c3a-444e-a6a6-5d1c14275c8f.png'>Download original image</a>

**Browser**: Chrome 70 (Windows 10)
**Referer**: [https://api.amexio.org/api/v5.3.1/index.html#/getting-started](https://api.amexio.org/api/v5.3.1/index.html#/getting-started)
**Screen size**: 1366 x 768 **Browser size**: 1366 x 657

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ketan-gote** [comment]
@kailaskokate122@gmail.com : Please find below stackblitz example, it has amexio-chart-d3 integration.

https://stackblitz.com/edit/amexio-d3-chart-example

**Comment by rashmithakkar** [comment]
Hi, 
You need to install d3 as well. -  **npm i d3**
and
import { HttpClientModule } from '@angular/common/http' in yout app.module.ts file and add HttpClientModule to imports.

After following this, if are still facing problem or having any other queries , please feel free to contact us.

Thank you
