### ISSUE TITLE
Amexio Data Grid for Django rest framework for JSON output

### ISSUE THREAD

**Issue by NightFury10** [meta-magic/amexio.github.io#105]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[x] Support request
</code></pre>

## Current behavior

json output from Django rest framework do not have data reader property as needed by Amexio Data Grid. 

## Expected behavior

Please can you help with getting the Grid work with DRF json output.

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

<div *ngFor="let City of City">
{{City.name}}
</div>
<amexio-datagrid title="City List "
 [data]="'data'" [page-size]="3">

 <amexio-data-table-column [data-index]="'name'" [data-type]="'string'" [hidden]="false" [text]="'Name'"
 (selectedRowData)="getSelectedData($event)">
 </amexio-data-table-column>
</amexio-datagrid>
import { Component, OnInit, ViewChild } from '@angular/core';
import { ApiMastersService } from '../api-masters.service';
import {
 AmexioWidgetModule,
 CommonDataService,
 AmexioFormsModule,
 AmexioDataModule,
 AmexioLayoutModule,
 AmexioPaneModule,
 AmexioNavModule,
 AmexioMediaModule,
 AmexioMapModule,
 AmexioChartsModule,
 AmexioDashBoardModule,
 AmexioEnterpriseModule
} from 'amexio-ng-extensions';

@Component({
 selector: 'app-city',
 templateUrl: './city.component.html',
 styleUrls: ['./city.component.css']
})
export class CityComponent implements OnInit {

private City: Object;

 constructor(private ApiMastersServices: ApiMastersService) { }

 ngOnInit() {
 this.getCity();
 }
 public getCity() {
 this.ApiMastersServices.getCity().subscribe(
 (data: Object) => {
 this.City = data;
 console.log(data);
 });
 }

}
CONSOLE.LOG
    (8) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
        0: {id: 1, name: "Nashik"}
        1: {id: 2, name: "Mumbai"}
        2: {id: 3, name: "Pune"}
        3: {id: 5, name: "Delhi"}
        4: {id: 9, name: "Aurangabad"}
        5: {id: 10, name: "Hyderabad"}
        6: {id: 11, name: "Bengaluru"}
        7: {id: 12, name: "Jaipur"}
        length: 8
        __proto__: Array(0)

ERROR TypeError: viewRows.forEach is not a function
    at AmexioDatagridComponent.push../node_modules/amexio-ng-extensions/amexio-ng-extensions.es5.js.AmexioDatagridComponent.setSelectedFlag (amexio-ng-extensions.es5.js:8746)

## What is the motivation / use case for changing the behavior?

There are majority of developers on Django platform which lags in dynamic templating such as components.

## Environment

<pre><code>
Angular version: 7

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by rashmithakkar** [comment]
Hi @NightFury10 ,

 Please find below stackblitz example, it has data grid example without data-reader.
**https://stackblitz.com/edit/amexio-grid-example**

**Comment by NightFury10** [comment]
Thank you it worked.
