### ISSUE TITLE
SA - phone number validation

### ISSUE THREAD

**Issue by arafkarsh** [meta-magic/amexio.github.io#106]
**Sender**: ritheshkdr@gmail.com
**Comment**: i have defining maxlength to the filed but it is not restricting.
[Open #29 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-1s6s/p/amexio-api-a0fddca1/29)

<a href='https://usersnappublic.s3.amazonaws.com/2019-02-11/08-27/2b4f409c-4760-448c-9806-c28edf7db173.png'>![SA - phone number validation](https://usersnappublic.s3.amazonaws.com/2019-02-11/08-27/1f57315b-ae0b-435c-8675-7c979a8c4678.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-02-11/08-27/2b4f409c-4760-448c-9806-c28edf7db173.png'>Download original image</a>

**Browser**: Chrome 72 (Windows 10)
**Referer**: [https://api.amexio.org/api/v5.5/index.html#/forms-Input/number-demo](https://api.amexio.org/api/v5.5/index.html#/forms-Input/number-demo)
**Screen size**: 1600 x 900 **Browser size**: 1600 x 757

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ketan-gote** [comment]
You can use our new directive for input mask. Please refer to below link for more info.

https://api.amexio.org/api/v5.14/#/directive-demo/input-mask
