### ISSUE TITLE
SA - Icons

### ISSUE THREAD

**Issue by arafkarsh** [meta-magic/amexio.github.io#107]
**Sender**: ritheshkdr@gmail.com
**Comment**: few icons are not displaying
[Open #30 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-1s6s/p/amexio-api-a0fddca1/30)

<a href='https://usersnappublic.s3.amazonaws.com/2019-02-11/11-06/579d2ba5-12d4-4457-9ee5-abb5eede4b45.png'>![SA - Icons](https://usersnappublic.s3.amazonaws.com/2019-02-11/11-06/5917b954-7f28-41aa-befb-f8a880855ce2.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-02-11/11-06/579d2ba5-12d4-4457-9ee5-abb5eede4b45.png'>Download original image</a>

**Browser**: Chrome 72 (Windows 10)
**Referer**: [https://api.amexio.org/api/v5.5/index.html#/navigation/sidenav-page-demo](https://api.amexio.org/api/v5.5/index.html#/navigation/sidenav-page-demo)
**Screen size**: 1600 x 900 **Browser size**: 2000 x 946

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ketan-gote** [comment]
This has been resolved.. Closing it.
