### ISSUE TITLE
SA - how do i apply material themes

### ISSUE THREAD

**Issue by arafkarsh** [meta-magic/amexio.github.io#108]
**Sender**: devbk999@gmail.com
**Comment**: Need support
[Open #31 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-1s6s/p/amexio-api-a0fddca1/31)

<a href='https://usersnappublic.s3.amazonaws.com/2019-03-03/21-53/70dd9009-6899-4a1b-b598-51c3a1a9a8aa.png'>![SA - how do i apply material themes](https://usersnappublic.s3.amazonaws.com/2019-03-03/21-53/6b7520f8-cf03-4128-8880-9d09a0bfb369.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-03-03/21-53/70dd9009-6899-4a1b-b598-51c3a1a9a8aa.png'>Download original image</a>

**Browser**: Chrome 72 (Windows 10)
**Referer**: [https://api.amexio.org/api/v5.7/index.html#/forms/html-form-demo](https://api.amexio.org/api/v5.7/index.html#/forms/html-form-demo)
**Screen size**: 1366 x 768 **Browser size**: 1093 x 500

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by rashmithakkar** [comment]
Hi,
whichever theme you want to apply , you can add it in angular.json in styles. 
(eg. ../node_modules/amexio-ng-extensions/styles/mda/at-md-army-olive.scss)
Check out various themes on [api docs](https://api.amexio.org/api/v5.15/index.html#/amexio-colors)
