### ISSUE TITLE
SA - Inline frid editing

### ISSUE THREAD

**Issue by arafkarsh** [meta-magic/amexio.github.io#111]
**Sender**: devbk999@gmail.com
**Comment**: need support
[Open #34 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-1s6s/p/amexio-api-a0fddca1/34)

<a href='https://usersnappublic.s3.amazonaws.com/2019-03-03/21-56/ba3aaec5-3413-4559-845e-4b3e733a019b.png'>![SA - Inline frid editing](https://usersnappublic.s3.amazonaws.com/2019-03-03/21-56/061195a7-9b21-402e-9761-fbd95d62bea0.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-03-03/21-56/ba3aaec5-3413-4559-845e-4b3e733a019b.png'>Download original image</a>

**Browser**: Chrome 72 (Windows 10)
**Referer**: [https://api.amexio.org/api/v5.7/index.html#/forms/html-form-demo](https://api.amexio.org/api/v5.7/index.html#/forms/html-form-demo)
**Screen size**: 1366 x 768 **Browser size**: 1093 x 500

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ketan-gote** [comment]
Sample as #24
