### ISSUE TITLE
SA - wanna ge only selected (checked) node from tree

### ISSUE THREAD

**Issue by arafkarsh** [meta-magic/amexio.github.io#114]
**Sender**: thakkar.nilesh10@gmail.com
**Comment**: Hi , i am using tree module in my project and need to display selected data node in right side of tree. as of now in api i get whole tree in with checked true. could you please help me on this 
thanks In advance
Nilesh
[Open #37 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-1s6s/p/amexio-api-a0fddca1/37)

<a href='https://usersnappublic.s3.amazonaws.com/2019-03-27/08-17/e00a5202-ac09-4155-8346-650376e3c4d2.png'>![SA - wanna ge only selected (checked) node from tree](https://usersnappublic.s3.amazonaws.com/2019-03-27/08-17/cf2108bf-ca14-46cd-b0dd-ff7b30e411f6.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-03-27/08-17/e00a5202-ac09-4155-8346-650376e3c4d2.png'>Download original image</a>

**Browser**: Chrome 72 (Linux)
**Referer**: [https://api.amexio.org/api/v5.9/index.html#/data/simple-tree-demo](https://api.amexio.org/api/v5.9/index.html#/data/simple-tree-demo)
**Screen size**: 1366 x 768 **Browser size**: 1366 x 599

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by rashmithakkar** [comment]
Please take the update of Amexio-5.9.2. Only the checked node data is emitted on checkbox selection.
