### ISSUE TITLE
SA - Tree map get clicked element

### ISSUE THREAD

**Issue by arafkarsh** [meta-magic/amexio.github.io#117]
**Sender**: chakermouhamed96@gmail.com
**Comment**: hello amexio team, 
i really like the work that you guys did ! and i wonder if it is possible to get the selected item in a tree map .. thanks in advance ofr your time.
Best Regards.
[Open #38 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-1s6s/p/amexio-api-a0fddca1/38)

<a href='https://usersnappublic.s3.amazonaws.com/2019-03-28/15-44/b7d05b5f-affb-44a6-b2f7-e4641c37d0c7.png'>![SA - Tree map get clicked element](https://usersnappublic.s3.amazonaws.com/2019-03-28/15-44/122a6346-0624-49a9-8de5-8f06a1298667.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-03-28/15-44/b7d05b5f-affb-44a6-b2f7-e4641c37d0c7.png'>Download original image</a>

**Browser**: Opera 58 (Windows 10)
**Referer**: [https://api.amexio.org/api/v5.9/index.html#/map/tree-map-demo](https://api.amexio.org/api/v5.9/index.html#/map/tree-map-demo)
**Screen size**: 1920 x 1080 **Browser size**: 1880 x 939

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by rashmithakkar** [comment]
Hi, 
Please take the latest update of Amexio (5.9.2) , You will find onClick event for treemap.
