### ISSUE TITLE
onClick does not fire for amexio-drop-down-menu

### ISSUE THREAD

**Issue by Ajitweb** [meta-magic/amexio.github.io#119]
The onClick **does not fire** for
```
<amexio-drop-down-menu [title]="'Sample'" [icon]="'fa fa-flash'"
 (onClick)="onDropDownMenuClick($event, mainTab)">
     <amexio-drop-down-menu-item [label]="'settings'" [icon]="'fa fa-home'">
     </amexio-drop-down-menu-item>
     <amexio-drop-down-menu-item [label]="'help center'" [separator]="true">
     </amexio-drop-down-menu-item>
     <amexio-drop-down-menu-item [label]="'Language'" [icon]="'fa fa-map-marker'">
     </amexio-drop-down-menu-item>
     <amexio-drop-down-menu-item [label]="'sign out'" [icon]="'fa fa-sign-out'">
     </amexio-drop-down-menu-item>
</amexio-drop-down-menu>
```

But **it fires** for
`        <amexio-drop-down-menu [icon-align]="'left'" [title]="'Payment option'" [data]="payment" [icon]="'fa fa-truck'"
          [transparent]="false" (onClick)="onDropDownMenuClick($event,mainTab)">
        </amexio-drop-down-menu>`

Am I missing anything?

Ajit

**Comment by rashmithakkar** [comment]
Hi Ajitweb,
You also need to add (onClick)="onDropDownMenuClick($event)" to <amexio-drop-down-menu-item> tag.

Please revert if you still find query
