### ISSUE TITLE
dropDown [data] seems not working

### ISSUE THREAD

**Issue by bigdatacreative** [meta-magic/amexio.github.io#12]
Hello There,

the setData function for dropDown component tries to split the dataReader option even if it's not set.
In the meantime this function doesn't take the [data] property into account...
As my data don't come from a json file, it's a bit annoying... : )
Is it a bug or I didn't get nothing ???

Thx for sharing the library!

nico

**Comment by pratikthecook** [comment]
Are you saying that the you aren't setting the dataReader property and you are binding a object which contains collection of object? 
Please post your the data that you are trying to bind.

**Comment by bigdatacreative** [comment]
Hi @pratikthecook !
Thx for your answer.
here's the element:

<amexio-dropdown name="menuList" [placeholder]="'Select a menu'" [(ngModel)]="selectedMenu" [data]="'data'" [dataReader]="menus" [displayField]="'name'" [valueField]="'id'" [width]="'250px'" (onSingleSelect)="onSelectMenu()"></amexio-dropdown>

menus is an object that contains data :

{
    "data": [
    {
        "name": "item1",
        "id": "59a3cfeece995543cd519522"
    },
    {
        "name": "item2",
        "id": "59a3cfeece995543cd519523"
    },
    {
        "name": "item3",
        "id": "59a3cfeece995543cd519524"
    },
    {
        "name": "item4",
        "id": "59a3cfeece995543cd519525"
    },
    {
        "name": "item5",
        "id": "59a3cfeece995543cd519526"
    },
    {
        "name": "item6",
        "menuItems": ["59a3d2811f48ce4255fe084e", "59a3d2811f48ce4255fe084f", "59a3d2811f48ce4255fe0850"],
        "id": "59a57a9a5387d9a0d5af51c2"
    },
    {
        "name": "item7",
        "menuItems": ["59a3d2811f48ce4255fe084e", "59a3d2811f48ce4255fe084f", "59a3d2811f48ce4255fe0850"],
        "id": "59a57a9a5387d9a0d5af51c3"
    }]
}

Thx so much for your help!
nico

**Comment by ketan-gote** [comment]
amexio-dropdown "dataReader" attribute value is set incorrectly

Your JSON structure is defined as below .. 
{
"data": [
{
"name": "item1",
"id": "59a3cfeece995543cd519522"
}.....
]}

Attribute name "data" of JSON needs to defined for "dataReader" attribute in amexio-dropdown tag, below is corrected amexio-dropdown tag.

<amexio-dropdown name="menuList" [placeholder]="'Select a menu'" [(ngModel)]="selectedMenu" [data]="'data'" [dataReader]="data" [displayField]="'name'" [valueField]="'id'" [width]="'250px'" (onSingleSelect)="onSelectMenu()">

**Comment by bigdatacreative** [comment]
Mmmm... Not sure I understand...

In my case :
[data] is an array (as described in doc) called 'menus' populated by a component.
the content of the array is :
[
{
    "name": "orgAdminMenu",
    "id": "59a3cfeece995543cd519522"
},
{
    "name": "orgManagerMenu",
    "id": "59a3cfeece995543cd519523"
},
...]

I don't understand what could/should be dataReader ?

**Comment by ketan-gote** [comment]
Hi @bigdatacreative 

Currently for amexio-dropdown the data which is getting binding to [data] needs to be JSON object which can have array . e.g

{
  "data": [
    {
      "name": "orgAdminMenu",
      "id": "59a3cfeece995543cd519522"
    }
  ]
}

please find amexio-dropdown markup for above datastructure.

<amexio-dropdown name="menuList" [placeholder]="'Select a menu'" [(ngModel)]="selectedMenu" [data]="'data'" [dataReader]="data" [displayField]="'name'" [valueField]="'id'" [width]="'250px'" (onSingleSelect)="onSelectMenu()">

We are enhancing our API to accommodate ARRAY also in next release.

**Comment by bigdatacreative** [comment]
Thx @ketan-gote. Already tried that but doesn't work 
In my case Dropdown is a child component and if I console.log data in the dropdown component ngOnInit I get undefined...

**Comment by pratikthecook** [comment]
@bigdatacreative Thanks for your suggestion, we have taken it into our account and getting the structure in working mode for data like yours.

**Comment by pratikthecook** [comment]
Hey @bigdatacreative we have fixed the issue! :)
Fixed with commit 045fc43a6fc4a45b8fd08d9a1c13b8e2dd11cacd
