### ISSUE TITLE
SA - New Issues

### ISSUE THREAD

**Issue by arafkarsh** [meta-magic/amexio.github.io#120]
**Sender**: ketan.gote@gmail.com
**Comment**: Testing by ketan
[Open #39 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-1s6s/p/amexio-api-a0fddca1/39)
**Notes**:
 - (1) There is issue with navbar

<a href='https://usersnappublic.s3.amazonaws.com/2019-04-13/12-21/62bc14c4-0024-400c-b4e6-2fbe914bdfc1.png'>![SA - New Issues](https://usersnappublic.s3.amazonaws.com/2019-04-13/12-21/3568d1fc-524e-453a-9ff1-f0265680b370.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-04-13/12-21/62bc14c4-0024-400c-b4e6-2fbe914bdfc1.png'>Download original image</a>

**Browser**: Chrome 73 (macOS Mojave)
**Referer**: [https://api.amexio.org/api/v5.9/index.html#/navigation/navbar-demo](https://api.amexio.org/api/v5.9/index.html#/navigation/navbar-demo)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 894

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ketan-gote** [comment]
Closing this issue.
