### ISSUE TITLE
Error when compile to production mode in  version 5.10 and 5.11

### ISSUE THREAD

**Issue by baminmru** [meta-magic/amexio.github.io#121]
![amexio_5 11bug](https://user-images.githubusercontent.com/16590085/57215671-4adac500-6ff6-11e9-8e3c-6a5f80ae8d2e.png)
## I'm submitting a...

<pre><code>
[ X] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

Error when compile to production mode in  version 5.10 and 5.11

## Expected behavior

Version 5.9 compiled without errors

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## Environment

<pre><code>
Angular version: 6.2.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.11.0  
- Platform: Windows 

Others:

</code></pre>

**Comment by rashmithakkar** [comment]
Please take the amexio-ng-extensions(v5.11.1) update .

Thanks

**Comment by baminmru** [comment]
Now version compiled successfully. Thank you.
