### ISSUE TITLE
Amexio-chart-d3 is not usefull in real dashboard, when data property used as series datasource

### ISSUE THREAD

**Issue by baminmru** [meta-magic/amexio.github.io#122]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

I use  JWT autentification in my application. So I can't use http-url property.
I fill data series array  from  server with different parameters.
I use data  property to set series information to chart.
I want  change series data for different items, but line chart only change legend information and not show chart series data at all.

## Expected behavior

Chart redraw legend and  series information when I change  series data and  set new array to data property.

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## Environment

<pre><code>
Angular version: 6.2.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X ] Firefox version 58
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.11.0 
- Platform: Windows   

Others:

</code></pre>

**Comment by baminmru** [comment]
You can see chart usage in  my  project
https://github.com/baminmru/A_monitor
See  DISPATCHER_CHART  component and DISPATCHER.service.ts

**Comment by rashmithakkar** [comment]
Please take the amexio-chart-d3 (v0.1.6) update 


Thanks

**Comment by baminmru** [comment]
This  version  work fine.
