### ISSUE TITLE
No record showing in Grouped grid when change 'data' property

### ISSUE THREAD

**Issue by baminmru** [meta-magic/amexio.github.io#123]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[X ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

I use JWT autentification in my application. So I can't use http-url property.
I fill data array from server with different parameters (for example each user has own scoupe of data records).
I use data property to set information to grid with 'groupby' property=true.
Grid not show rows at all.

If 'groupby'  property = false grid behavior is OK.

## Expected behavior

Grid show actual grouped rows  when data  property set to new collection of data rows. 

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## Environment

<pre><code>
Angular version: 6.2.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ X] Firefox version 58
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.11.0  
- Platform:  Windows 

Others:

</code></pre>

**Comment by rashmithakkar** [comment]
Please take the amexio-ng-extensions(v5.11.1) update.

Thanks

**Comment by baminmru** [comment]
Now  grid show records, but group by feature do not  work.  And also rowSelect event not  raised.
