### ISSUE TITLE
unable to build AOT

### ISSUE THREAD

**Issue by vikram06** [meta-magic/amexio.github.io#124]
I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
While running and JIT working fine.But when build AOT getting
`ERROR in node_modules\amexio-ng-extensions\amexio-ng-extensions.d.ts.ɵci.html(3,50): : Expected 1 arguments, but got 2.`

## Expected behavior
Expecting AOT Build success 

## Environment

<pre><code>
Angular version: 7.2.0

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 

</code></pre>

**Comment by rashmithakkar** [comment]
Please take the amexio-ng-extensions(v5.11.1) update.

Thanks

**Comment by vikram06** [comment]
Thanks @rashmithakkar 
Now getting 
```
ERROR in ./node_modules/amexio-ng-extensions/amexio-ng-extensions.es5.js 61:9
Module parse failed: Identifier '__extends' has already been declared (61:9)
You may need an appropriate loader to handle this file type.
|     return extendStatics(d, b);
| };
> function __extends(d, b) {
|     extendStatics(d, b);
|     function __() { this.constructor = d; }
```

**Comment by priyavenkat95** [comment]
I am also facing the same error. Is there any solution for this error?

**Comment by vikram06** [comment]
No updates from @rashmithakkar . So i switched to an another framework.

**Comment by priyavenkat95** [comment]
I want to know which framework did you use?

**Comment by rashmithakkar** [comment]
@priyavenkat95 May I please know which amexio version are you using?

**Comment by vikram06** [comment]
@priyavenkat95 I am using e-charts

**Comment by priyavenkat95** [comment]
I am using amexio versions are "amexio-chart-d3": "0.1.9",  "amexio-ng-extensions": "5.18.0"

**Comment by rashmithakkar** [comment]
@priyavenkat95  Can you share the versions of Angular CLI, Node and Angular that you are using?

**Comment by priyavenkat95** [comment]
@rashmithakkar I am using
Angular CLI: 7.3.9
Node: 8.10.0
Angular: 7.2.15

**Comment by rashmithakkar** [comment]
@priyavenkat95 Can you please take the update of amexio 5.18.1 and do tell if you are still facing the issue.

**Comment by priyavenkat95** [comment]
@rashmithakkar Thanks for your response. My problem was fixed. I downgrade the versions like "amexio-chart-d3": "0.1.1", "amexio-ng-extensions": "5.5.3". It works perfectly for my problem.
