### ISSUE TITLE
amexio-layout-grid  is broken in version 5.11.1

### ISSUE THREAD

**Issue by baminmru** [meta-magic/amexio.github.io#125]
## I'm submitting a...

<pre><code>
[ X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

Grid-layout do not work. See sample at 
https://api.amexio.org/api/v5.11/#/layout/gridlayout-demo

## Expected behavior

Grid-layout  work as in prevous versions.

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## Environment

<pre><code>
Angular version: 6.2.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ X] Firefox version 58
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.11
- Platform:  Windows 

Others:

</code></pre>

**Comment by ketan-gote** [comment]
@baminmru - We have verified this in latest version and it is working. Can you reverify at your end and let us know. If issue is still present, please share stackblitz example, as it will help us in investigating further. 
Also you can close this issue if it is resolve.

**Comment by baminmru** [comment]
Sorry, but what latest version you verify?
This feature do not  work at your demo site for all 5.1x version.
Here:  https://api.amexio.org/api/v5.14/#/layout/gridlayout-demo
And here:  https://api.amexio.org/api/v5.13/#/layout/gridlayout-demo
And here: https://api.amexio.org/api/v5.12/#/layout/gridlayout-demo 
And here: https://api.amexio.org/api/v5.11/#/layout/gridlayout-demo 

'Live page' used amexio 5.4 where layout work ok.

**Comment by baminmru** [comment]
![изображение](https://user-images.githubusercontent.com/16590085/59706273-c2f8f500-9208-11e9-808e-0cb1ddc667a6.png)

Browser version is Firefox 67.0.2

**Comment by arafkarsh** [comment]
It's working in Chrome and Microsoft Edge Browser and not working in FireFox. We will look into this asap.
![Amexio-API-Edge](https://user-images.githubusercontent.com/11264297/59709627-e467da00-9224-11e9-9679-2d1fd46e1b79.jpg)

**Comment by baminmru** [comment]
I hope you fix problem for FireFox. Without this fix I cannot use new version of Amexio in my projects  :-(

**Comment by ketan-gote** [comment]
@baminmru - We are looking into this issue and fix will be supporting FireFox also.

**Comment by arafkarsh** [comment]
We will be releasing the fix today.

**Comment by arafkarsh** [comment]
Checked the fix in the following Browsers
- FireFox
- Chrome
- Safari
- Edge
- Opera

![Amexio-fix-Grid-Layout-FireFox](https://user-images.githubusercontent.com/11264297/59819213-8af6cc80-9344-11e9-9f4b-076b724840f6.jpg)
![Amexio-fix-Grid-Layout-Chrome](https://user-images.githubusercontent.com/11264297/59819239-9d710600-9344-11e9-8be3-62870c27f99d.jpg)
![Amexio-fix-Grid-Layout-Safari](https://user-images.githubusercontent.com/11264297/59819255-ac57b880-9344-11e9-98cd-9d8e8763b707.jpg)
![Amexio-fix-Grid-Layout-Edge](https://user-images.githubusercontent.com/11264297/59819266-bb3e6b00-9344-11e9-941a-3710f17ac0d5.jpg)

**Comment by baminmru** [comment]
Thanks, I am waiting while next release is ready.

**Comment by rashmithakkar** [comment]
Above issue is resolved in amexio version 5.14.3.  
Please refer [Sample grid layout] (https://stackblitz.com/edit/amexio-v4-gridlayoutbasic-latest1?file=app/app.component.ts) with latest version.
