### ISSUE TITLE
Amexio Datagrid Filtering

### ISSUE THREAD

**Issue by teatherconsulting** [meta-magic/amexio.github.io#127]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

Currently if you have a amexio-datagrid and you enabled the enable-data-filter property it allows you to correctly filter the data.  However, if you have multiple pages of data it still displays all of the pages of data at the bottom of the grid even though after filtering there may only be a single page of data.  It is even more confusing if you happen to have multiple pages of filtered data.  It looks like you should be able to click on one of the page numbers at the bottom, but clicking on them actually clears the filter.

## Expected behavior

It would be great if filtering could actually filter the page numbers at the bottom as well and the page numbers at the bottom would apply to the filter.  For example, if you have 50 pages of data and the filter results in 2 pages, then there would only be a 1 and 2 page numbers at the bottom.  Then it would allow you to click on page 1 or 2 to go to that page of filtered data without clearing out the filter.

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## What is the motivation / use case for changing the behavior?

We use the grid to display a large amount of data (often 50-100 pages of data).  It is working great, but the filtering is difficult to use because of the paging issue.  We would love to continue using the built in filtering since it easily allows client-side filtering, but need the way that the paging with filters is working.

## Environment

<pre><code>
Angular version: We are currently using 7.0.1

Browser:
- [X ] Chrome (desktop) version XX
- [X ] Chrome (Android) version XX
- [X ] Chrome (iOS) version XX
- [X ] Firefox version XX
- [ X] Safari (desktop) version XX
- [X ] Safari (iOS) version XX
- [ X] IE version XX
- [X ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by DatsGawas** [comment]
Hi teatherconsulting, 
 we have fixed this issue, Please find working functionality in next point release.

**Comment by teatherconsulting** [comment]
The filtering does work as we expect.  However, now it seems like you can't clear out a filter.  For example, if I type in an a, then it filters and only displays the items that start with an a.  However, if I remove the a it isn't possible to get back the entire list without refreshing the table from scratch again.  Can we make it so it will clear out the filter if you remove the data from the textbox again?
