### ISSUE TITLE
Clear Filter

### ISSUE THREAD

**Issue by teatherconsulting** [meta-magic/amexio.github.io#129]
The filtering does work as we expect after the fix for #127.  However, now it seems like you can't clear out a filter.  For example, if I type in an a, then it filters and only displays the items that start with an a.  However, if I remove the a it isn't possible to get back the entire list without refreshing the table from scratch again.  Can we make it so it will clear out the filter if you remove the data from the textbox again?

_Originally posted by @teatherconsulting in https://github.com/meta-magic/amexio.github.io/issues/127#issuecomment-497055295_

**Comment by teatherconsulting** [comment]
Any update on when there might be a fix for this?  The last update made the grid even less usable than it was before, so we aren't able to use the most recent version.

**Comment by arafkarsh** [comment]
Will look into this asap. Regret the inconvenience caused.

**Comment by arafkarsh** [comment]
Check out the Demo in the latest API docs.
https://api.amexio.org/api/v5.14/#/data/filter-grid-demo 
The team is working on stackblitz examples also.

**Comment by kedar8** [comment]
check out the stackblitz example of the grid filter. 
1) Column Grid Filter -
https://stackblitz.com/edit/amexio-v4-filter-grid-test?embed=1&file=app/grid/filtergrid/filtergrid.demo.html&view=editor
2) Global Grid Filter -
https://stackblitz.com/edit/amexio-v4-global-filter-grid?embed=1&file=app/grid/filtergrid/filtergrid.demo.html&view=editor

**Comment by teatherconsulting** [comment]
Your filter grid demo actually has the exact same bug we are seeing in our grid and are hoping you can fix.  For example, if you go to the stackblitz example you provided and then go to the preview.  Then search for male in the Job Title field.  It will bring up only the first record with looks great.  However, if you remove male from the search box only the first record still appears.  It actually isn't possible regardless of what you do to clear the search and get the rest of the records back.  Let me know if there is any other information that would be helpful.

**Comment by arafkarsh** [comment]
It's clear now. We will fix this asap. Thanks for the support.

**Comment by ketan-gote** [comment]
@teatherconsulting - This issue is fixed in our latest release (5.14.2). Please find corresponding stackblitz example.
https://stackblitz.com/edit/amexio-grid-filter-new-demo?embed=1&file=src/app/gridfilter/filtergrid.demo.component.html&view=editor
