### ISSUE TITLE
SA - Rado : Event fired twice

### ISSUE THREAD

**Issue by arafkarsh** [meta-magic/amexio.github.io#134]
**Sender**: contact@dlucazeau.fr
**Comment**: The method called by onSelection on a radio-group is fired twice.
How can we avoid this?
Thanks
[Open #41 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-1s6s/p/amexio-api-a0fddca1/41)

<a href='https://usersnappublic.s3.amazonaws.com/2019-06-26/10-42/8f06027d-38dd-42ad-af1b-181316d2ab57.png'>![SA - Rado : Event fired twice](https://usersnappublic.s3.amazonaws.com/2019-06-26/10-42/586be056-249b-4472-a687-3a7e750c47ec.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-06-26/10-42/8f06027d-38dd-42ad-af1b-181316d2ab57.png'>Download original image</a>

**Browser**: Firefox 68 (Windows 10)
**Referer**: [https://api.amexio.org/api/v5.14/#/forms-Input/radiogroup-demo](https://api.amexio.org/api/v5.14/#/forms-Input/radiogroup-demo)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 908

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by rashmithakkar** [comment]
Please take the latest update (amexio-ng-extensions)
