### ISSUE TITLE
Amexio-d3-chart.  Rotation for long label at x-Axis

### ISSUE THREAD

**Issue by baminmru** [meta-magic/amexio.github.io#137]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

Data at x-Axis are overlaps if label is long or count of label is big.

## Expected behavior

Rotate label to fixed angle. For example as here: http://www.d3noob.org/2013/01/how-to-rotate-text-labels-for-x-axis-of.html

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by rashmithakkar** [comment]
@baminmru 

Can you please share example on stackblitz.. So it is easy for us to solve the issue

**Comment by rashmithakkar** [comment]
@baminmru 

Please refer the [api docs](https://api.amexio.org/api/v5.18/index.html#/D3chart/amexio-d3-chart-line) . If data is huge, x axis gets intervals and chart is plotted and have provided slant as a input which makes x axis label rotate.
