### ISSUE TITLE
Showcase page (API page) not showing all the components on chrome

### ISSUE THREAD

**Issue by nni123** [meta-magic/amexio.github.io#14]
http://www.amexio.org/showcaseapp/v2/index.html#/home

Open above URL in three browsers

[1]  Chrome (latest build 61). You can't navigate pass Dashboard (left-side side frame). Map is invisible. 

[2] It works on Firefox (build 55). 

[3] Microsoft Edge is the only browser where you can see left-side frame with all the options (Map is last one) without cutoff.

It is not a bug in build, but newbie can't find Map or Showcase API if they're using chrome (which default for most of the developers).

Thanks for the library & roadmap look awesome (VS plug in as well)

**Comment by arafkarsh** [comment]
![amexio-showcase-app](https://user-images.githubusercontent.com/11264297/30513087-1e2714e8-9b1b-11e7-80d2-00a631fd619e.jpg)

**Comment by arafkarsh** [comment]
The actual issue - Scroll Bar is not working when the Browser height is less then the left menus. Checkout the issue below.. 
![amexio-showcase-app-issue-2](https://user-images.githubusercontent.com/11264297/30513139-cb726e40-9b1b-11e7-8c11-c043dc755755.jpg)

**Comment by nni123** [comment]
[1] Chrome browser 61 on windows 10
![image 000](https://user-images.githubusercontent.com/31043903/30516444-830a8c86-9af4-11e7-9234-9903ad9cfd87.jpg)

[2] Microsoft Edge on window 10
![image 001](https://user-images.githubusercontent.com/31043903/30516453-b3199ff2-9af4-11e7-9df0-31ffed0df4a3.jpg)

**Comment by arafkarsh** [comment]
we are looking into this issue and we will fix it asap.

**Comment by DatsGawas** [comment]
fixed.
