### ISSUE TITLE
The filtering and/or sorting for the Data Grid is not remaining as we would expect when the data in the table is refreshed.

### ISSUE THREAD

**Issue by jeffipson** [meta-magic/amexio.github.io#140]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
We have an amexio-datagrid with the [data] tag set to "references." "references" is just an array of data objects that we want displayed in the Data Grid and it displays correctly, as seen below. We also can update the "references" array and the Data Grid will automatically update and is working as expected.

![image](https://user-images.githubusercontent.com/26435472/67022940-3af40080-f0bf-11e9-85ac-624be67fb6c2.png)

We can sort by the "First Name" property by typing in "Deb" into the text area and it filters only the data in "references" with "Deb" in the "First Name" and removes the rest, as seen below. This is what we would expect and is working correctly. 

![Capture](https://user-images.githubusercontent.com/26435472/67023000-5101c100-f0bf-11e9-920c-a3bdb384c91e.PNG)

HOWEVER, if we have the data filtered (like in the example above) -and- then refresh "references"....the Data Grid will refresh, but it is not filtered anymore even though the text "Deb" remains in the filter field and we would expect it to still show the filtered data still. It shows all the data as if we didn't have anything filtered at all. This is not working as expected.

![Capture (1)](https://user-images.githubusercontent.com/26435472/67023040-61b23700-f0bf-11e9-96fe-0eae93c2c5ca.PNG)

The same thing occurs with sorting the data by the column. If we have it previously sorted and then refresh "references," the Data Grid displays the refreshed data, but it is no longer sorted anymore like we would expect it to be.

## Expected behavior
We would expect the filtering and/or sorting for the Data Grid to remain in place when the data in the table is refreshed.

**Comment by rashmithakkar** [comment]
Hi @jeffipson Please take the update of amexio-ng-extensions 5.20.2. 


Please revert if you still face any issue.

**Comment by jeffipson** [comment]
Thank you! We have updated in a test environment and are verifying the changes, but so far all looks good. Thanks!

**Comment by jeffipson** [comment]
We have found that the Data Grid does not retain the sorting after the data has been refreshed. The filtering appears to be working as expected, but the sorting does NOT. Can you look at the sorting please?

_"The same thing occurs with sorting the data by the column. If we have it previously sorted and then refresh "references," the Data Grid displays the refreshed data, but it is no longer sorted anymore like we would expect it to be."_
