### ISSUE TITLE
SA - Testing Issue

### ISSUE THREAD

**Issue by arafkarsh** [meta-magic/amexio.github.io#15]
**Sender**: pratik.kelwalkar@metamagic.in
**Comment**: Spacing in menus
[Open #7 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-1s6s/p/amexio-api-a0fddca1/7)
**Notes**:
 - (1) Spacing Left

<a href='https://usersnappublic.s3.amazonaws.com/2017-09-18/16-24/c69a1f08-036e-43eb-b48c-b9c8268e53ab.png'>![SA - Testing Issue](https://usersnappublic.s3.amazonaws.com/2017-09-18/16-24/887898a0-7f31-430e-84c2-a839ffba4f96.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-09-18/16-24/c69a1f08-036e-43eb-b48c-b9c8268e53ab.png'>Download original image</a>

**Browser**: Chrome 61 (Linux)
**Referer**: [http://amexio.org/showcaseapp/v2/index.html#/home](http://amexio.org/showcaseapp/v2/index.html#/home)
**Screen size**: 1366 x 768 **Browser size**: 1366 x 643

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ketan-gote** [comment]
Its fixed in showcase application.
