### ISSUE TITLE
[Request] Any plan to release material design template or enterprise source code

### ISSUE THREAD

**Issue by nni123** [meta-magic/amexio.github.io#16]
[1] New version with the material design looks pretty good.
http://www.amexio.org/demoapp/

Any plan to release the source code of enterprise or material design template.

[2] Do you have anything in the pipeline to remove jQuery and browser DOM dependencies from components?

Thanks

**Comment by ketan-gote** [comment]
Source code for both app is on github
Demo App - https://github.com/meta-magic/amexio-theme
Enterprise - https://github.com/meta-magic/amexioFlixPoc

**Comment by nni123** [comment]
Thanks for the links.

[1] Demo App link is incorrect but I found the right one here

https://github.com/meta-magic/amexio-demoapp-theme

[2] Enterprise source code got local address for the following dependency 

    "amexio-ng-extensions": "file:../amexio.github.io/dist/amexio-ng-extensions-2.1.5.tgz",

Can you please let me the correct address?

Thanks

**Comment by nni123** [comment]
solved the issue. I found the link for the latest version in another project build.

    "amexio-ng-extensions": {
      "version": "3.0.0",
      "resolved": "https://registry.npmjs.org/amexio-ng-extensions/-/amexio-ng-extensions-3.0.0.tgz",
      "integrity": "sha512-uQXWoBcfdBL3NvK8bOx4BLmjkizW/aeDcNDsReVrccxsGyZgKQszjZSDAm1JGt2l+xbHdAKjfkwu0yCnZoMHCw=="
    },
