### ISSUE TITLE
SA - THANK YOU! The great job!!!!

### ISSUE THREAD

**Issue by arafkarsh** [meta-magic/amexio.github.io#19]
**Sender**: hryhoriy.kravtsov@gmail.com
**Comment**: Dear authors!

Thank you very much for the incredible set of widgets for Angular 4 - it is really the super set!!! Thank you!

I would like to ask the following: can I get binding through some attribute to validation result for inputs components? Will be very thank you for any reply.

Kind regards,
Dr. Hryhoriy Kravtsov

[Open #8 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-1s6s/p/amexio-api-a0fddca1/8)

<a href='https://usersnappublic.s3.amazonaws.com/2017-10-10/22-19/0b5bd4b7-a80c-45e8-8c67-f9f42945aa59.png'>![SA - THANK YOU! The great job!!!!](https://usersnappublic.s3.amazonaws.com/2017-10-10/22-19/7e4d524f-83e9-4f44-b1fe-84c8899d0486.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-10-10/22-19/0b5bd4b7-a80c-45e8-8c67-f9f42945aa59.png'>Download original image</a>

**Browser**: Chrome 61 (Ubuntu)
**Referer**: [http://www.amexio.org/showcaseapp/v3/index.html#/home](http://www.amexio.org/showcaseapp/v3/index.html#/home)
**Screen size**: 1366 x 768 **Browser size**: 1301 x 653

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ketan-gote** [comment]
We have commonservice which can be used for amexio-components validation. @DatsGawas will create small example on plunker and send you.

**Comment by DatsGawas** [comment]
Hi,
I have created plunker which will give you idea about how component can be validate.
[https://plnkr.co/edit/bHfWM3szKELZFiccjsdX?p=preview](https://plnkr.co/edit/bHfWM3szKELZFiccjsdX?p=preview)
