### ISSUE TITLE
Matrial 2 theming issues

### ISSUE THREAD

**Issue by nni123** [meta-magic/amexio.github.io#20]
Please see the attached image of email inputfield. If you don't provide correct email address "x" should be in center with error message the bottom of textfield.

Here is the theme info from angular-cli.json file.

`        "../node_modules/bootstrap/dist/css/bootstrap.css",
        "../node_modules/font-awesome/css/font-awesome.min.css",
        "../node_modules/amexio-ng-extensions/themes/material/MAT-amber.css"        
`
![image 000](https://user-images.githubusercontent.com/31043903/31421005-c356a5e6-adf9-11e7-8f09-0d01931700fd.jpg)

Thank you

**Comment by ketan-gote** [comment]
Will check it and get back to you.

**Comment by sagarjadhav968** [comment]
this issue is fixed available  in v3.0.1
