### ISSUE TITLE
DataGrid performance issue with 80k records in local datastore 

### ISSUE THREAD

**Issue by nni123** [meta-magic/amexio.github.io#21]
Datagrid demo code read modified country.JSON (80k record) with the page size of 10k.  

After I start server localhost:4200 take-ups forever to load (maybe 3-5 minutes to get initial dataset). I get following error messages in chrome developer tools. FireFox throw error "script stop working or taking too long to execute...something like that"
 
`vendor.bundle.js:54277 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
chrome-extension://kbfnbcaeplbcioakkpcpgfkobkghlhen/src/js/bundle.js:17755 Uncaught RangeError: Maximum call stack size exceeded
    at MutationObserver.r (chrome-extension://kbfnbcaeplbcioakkpcpgfkobkghlhen/src/js/bundle.js:17755)
bundle.js:21890 [Violation] 'setTimeout' handler took 53ms
bundle.js:21890 [Violation] 'setTimeout' handler took 51ms
bundle.js:21890 [Violation] 'setTimeout' handler took 76ms
bundle.js:21890 [Violation] 'setTimeout' handler took 55ms
bundle.js:21890 [Violation] 'setTimeout' handler took 55ms
bundle.js:21890 [Violation] 'setTimeout' handler took 68ms
bundle.js:21890 [Violation] 'setTimeout' handler took 63ms
bundle.js:21890 [Violation] 'setTimeout' handler took 51ms
bundle.js:21890 [Violation] 'setTimeout' handler took 52ms
bundle.js:21890 [Violation] 'setTimeout' handler took 53ms
bundle.js:21890 [Violation] 'setTimeout' handler took 59ms
bundle.js:21890 [Violation] 'setTimeout' handler took 52ms
`

My modification to demo code is simple pageSize =10000 and add more country names to country.JSON (80k rows). 

Is it JQuery performance hit or lazyloading is a better option?
Thanks

**Comment by pratikthecook** [comment]
We have recreated your scenario and found no issue wth 80k+ records and 10000 page size.Are you using Angular CLI? If so please mention version number. Also please open the issue with the format given.

**Comment by nni123** [comment]
I can reopen the issue with the new format.
