### ISSUE TITLE
SA - DropDown does not work with lazy loading

### ISSUE THREAD

**Issue by arafkarsh** [meta-magic/amexio.github.io#23]
**Sender**: hryhoriy@tripcombi.com
**Comment**: Hey! 

Dropbox doesn't re-render (re-construct) the list of items if the items are being created in promise (lazy loading). 
I cannot use http link bc items can be only obtained by get with authorization tocken in the http headers.
[Open #9 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-1s6s/p/amexio-api-a0fddca1/9)

<a href='https://usersnappublic.s3.amazonaws.com/2017-10-20/16-45/45a10d9a-3b4e-4778-ae16-f3c8a02a4b0c.png'>![SA - DropDown does not work with lazy loading](https://usersnappublic.s3.amazonaws.com/2017-10-20/16-45/5b684246-e274-4191-a9c3-31285d06b4e9.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-10-20/16-45/45a10d9a-3b4e-4778-ae16-f3c8a02a4b0c.png'>Download original image</a>

**Browser**: Chrome 61 (Ubuntu)
**Referer**: [http://www.amexio.org/showcaseapp/v3/index.html#/dropdwnsearch](http://www.amexio.org/showcaseapp/v3/index.html#/dropdwnsearch)
**Screen size**: 1920 x 1080 **Browser size**: 1873 x 990

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by pratikthecook** [comment]
Change Detection has been fixed. DropDown now works re-rendering data. Commit f3e167bc9e53793a3359b3a8956aeb76f027dc8b
