### ISSUE TITLE
SA - Feedback Testing

### ISSUE THREAD

**Issue by arafkarsh** [meta-magic/amexio.github.io#25]
**Sender**: araf.karsh@metamagic.in
**Comment**: Check the attached comment
[Open #1 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-1s6s/p/amexio-api-a0fddca1/1)
**Notes**:
 - (1) ... Checkbox functionality and a simple customizable ....

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-12/13-16/56a614a4-fb87-48a6-8361-2c9e49a97acf.png'>![SA - Feedback Testing](https://usersnappublic.s3.amazonaws.com/2017-07-12/13-16/64351692-9982-4e9d-ad5e-1603c1a8191d.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-12/13-16/56a614a4-fb87-48a6-8361-2c9e49a97acf.png'>Download original image</a>

**Browser**: Chrome 59 (macOS Sierra)
**Referer**: [http://www.amexio.org/metamagic-showcase/index.html#/treecheckbox](http://www.amexio.org/metamagic-showcase/index.html#/treecheckbox)
**Screen size**: 1920 x 1200 **Browser size**: 1372 x 1036

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ketan-gote** [comment]
Closing the issue.
