### ISSUE TITLE
Bootstrap sass instead of Bootstrap css

### ISSUE THREAD

**Issue by abhinavsachdeva2701** [meta-magic/amexio.github.io#27]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x ] Support request
</code></pre>

## Current behavior

In Angular-cli.json file, instead of pointing to bootstrap css, if it is pointed to bootstrap sass, amexio components are not rendering properly. In angular-cli.json i have included
"styles": [
        "assets/styles/vendor.scss",
        "assets/styles/styles.scss",

vendor.scss consist of
$icon-font-path: "~bootstrap-sass/assets/fonts/bootstrap/";
@import
  '~bootstrap-sass/assets/stylesheets/bootstrap';

By this way amexio components are not rendering properly. Even after including bootstrap sass do i need to still include bootstrap css

## Expected behavior

Components should render properly with bootstrap sass

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## What is the motivation / use case for changing the behavior?

I am using amexio component for developing production application, and since we are using bootstrap 4 which is made up in sass(scss), i only want to point to bootstrap sass like this in a scss file and include this scss file in angular-cli.json
$icon-font-path: "~bootstrap-sass/assets/fonts/bootstrap/";
@import
  '~bootstrap-sass/assets/stylesheets/bootstrap';

## Environment

<pre><code>
Angular version: X.Y.Z

Angular 2
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by DatsGawas** [comment]
Which Angular CLI Version are you using ? As older versions of CLI needed to set a explicit flag for SCSS
`ng set defaults.styleExt scss` . We have reproduced the issue and set the angular-cli.json to
```
"styles": [
"../node_modules/bootstrap/scss/bootstrap.scss",
"assets/styles/styles.scss",
]
```
And Found no issue's. 
Angular CLI Version :` 1.4.3`
