### ISSUE TITLE
SA - Support for version 5 of angularjs 5

### ISSUE THREAD

**Issue by arafkarsh** [meta-magic/amexio.github.io#28]
**Sender**: ronald_ram@hotmail.com
**Comment**: When can we use AMEXIO with version 5 of Angular?
[Open #12 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-1s6s/p/amexio-api-a0fddca1/12)

<a href='https://usersnappublic.s3.amazonaws.com/2017-11-27/16-05/299c58ae-79da-4e42-a995-f86e77e1a0a7.png'>![SA - Support for version 5 of angularjs 5](https://usersnappublic.s3.amazonaws.com/2017-11-27/16-05/2a3618e6-dd3b-4bc1-8616-acde5dcda999.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-11-27/16-05/299c58ae-79da-4e42-a995-f86e77e1a0a7.png'>Download original image</a>

**Browser**: Chrome 62 (Windows 7)
**Referer**: [http://www.amexio.org/showcaseapp/v3/index.html#/home](http://www.amexio.org/showcaseapp/v3/index.html#/home)
**Screen size**: 1366 x 768 **Browser size**: 1366 x 637

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by pratikthecook** [comment]
We have this planned in the upcoming weekly release.

**Comment by OnlyZero** [comment]
Thanks, I look forward to this
