### ISSUE TITLE
SA - Download Counter

### ISSUE THREAD

**Issue by arafkarsh** [meta-magic/amexio.github.io#3]
**Sender**: Araf.karsh@metamagic.in
**Comment**: Counter icon not working
[Open #3 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-1s6s/p/amexio-api-a0fddca1/3)
**Notes**:
 - (1) Counter Icon missing....

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-17/06-33/afd5e855-0e81-4a56-a27b-8a4870cb94e9.png'>![SA - Download Counter](https://usersnappublic.s3.amazonaws.com/2017-07-17/06-33/00f1e9a7-c3d6-4437-beac-9deaac558bda.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-17/06-33/afd5e855-0e81-4a56-a27b-8a4870cb94e9.png'>Download original image</a>

**Browser**: Safari 10 (macOS Sierra)
**Referer**: [http://www.amexio.org/metamagic-showcase/index.html#/home](http://www.amexio.org/metamagic-showcase/index.html#/home)
**Screen size**: 1920 x 1200 **Browser size**: 1536 x 1011

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by pratikthecook** [comment]
Fixed
