### ISSUE TITLE
I find a datagrid bug 

### ISSUE THREAD

**Issue by lefthand250** [meta-magic/amexio.github.io#31]
## I'm submitting a datagrid bug 

<pre><code>
i find a datagrid bug in amexio-ng-extensions.umd.js line 1708

  /**
     * @param {?} httpResponse
     * @return {?}
     */
    DataTableComponent.prototype.getResponseData = /**
     * @param {?} httpResponse
     * @return {?}
     */
    function (httpResponse) {
        var /** @type {?} */ responsedata = httpResponse;
        var /** @type {?} */ dr = this.dataReader.split('.');
        for (var /** @type {?} */ ir = 0; ir < dr.length; ir++) {
            responsedata = responsedata[dr[ir]];
        }
        return responsedata;
    };
 when i blind data by dataTableBindData,it will ERROR TypeError: Cannot read property 'split' of undefined
i found it doesnot judge the 'this.dataReader'

</code></pre>

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [ ] Chrome (desktop) version  62.0.3202.89

 
For Tooling issues:
- Node version: v8.9.1
- Platform:   Windows 

</code></pre>

**Comment by sagarjadhav968** [comment]
Can you send dataTableBindData data and HTML tag of amexio datagrid which you written  in HTML file...

**Comment by lefthand250** [comment]
thanks for your reply。this is my  HTML tag and my dataTableBindData data 
html:
<amexio-card-pane>
              <amexio-pane-header>
               Data Grid
              </amexio-pane-header>
              <amexio-pane-body>
                <amexio-data-table
                  [title]="'Data Grid'"
                  [pageSize] = "10"
                  
                  [checkboxSelect]="true"
                  [dataTableBindData]="options"
                  (selectedRowData)="onRowSelect($event)"
                  (rowSelect)="onRowClick($event)">
                  <amexio-data-table-column [dataIndex]="'countryName'" [dataType]="'string'" [hidden]="false" [text]="'Name'">
                    
                  </amexio-data-table-column>
                  <amexio-data-table-column [dataIndex]="'capital'" [dataType]="'string'" [hidden]="true" [text]="'Capital'"></amexio-data-table-column>
                  <amexio-data-table-column [dataIndex]="'countryCode1'" [dataType]="'string'" [hidden]="false" [text]="'Code1'"></amexio-data-table-column>
                  <amexio-data-table-column [dataIndex]="'countryCode2'" [dataType]="'string'" [hidden]="false" [text]="'Code2'"></amexio-data-table-column>
                  <amexio-data-table-column [dataIndex]="'countryFlag'" [dataType]="'string'" [hidden]="false" [text]="'Flag'"></amexio-data-table-column>
                  <amexio-data-table-column [dataIndex]="'isoNumeric'" [dataType]="'number'" [hidden]="false" [text]="'ISO'" [summaryCaption]="'Sum'" [summaryType]="'sum'">
                  </amexio-data-table-column>
                </amexio-data-table>
              </amexio-pane-body>
            </amexio-card-pane>  


dataTableBindData:
this.options = [
      {
        "countryName": "Myanmar",
        "countryCode1": "MM",
        "countryCode2": "MMR",
        "countryFlag": "MM.png",
        "capital": "",
        "currencyCode": "MMK",
        "currencyName": "Kyat",
        "currencySymbol": "K",
        "capitalLatitude": null,
        "capitalLongitude": null,
        "isoNumeric": 104
      },
      {
        "countryName": "U.S. Virgin Island",
        "countryCode1": "VI",
        "countryCode2": "VIR",
        "countryFlag": "VI.png",
        "capital": "",
        "currencyCode": "USD",
        "currencyName": "Dollar",
        "currencySymbol": "$",
        "capitalLatitude": null,
        "capitalLongitude": null,
        "isoNumeric": 850
      },
      {
        "countryName": "Latvia",
        "countryCode1": "LV",
        "countryCode2": "LVA",
        "countryFlag": "LV.png",
        "capital": "",
        "currencyCode": "LVL",
        "currencyName": "Lat",
        "currencySymbol": "Ls",
        "capitalLatitude": null,
        "capitalLongitude": null,
        "isoNumeric": 428
      },
      {
        "countryName": "British Indian Ocean Teritory",
        "countryCode1": "IO",
        "countryCode2": "IOT",
        "countryFlag": "IO.png",
        "capital": "",
        "currencyCode": "USD",
        "currencyName": "Dollar",
        "currencySymbol": "$",
        "capitalLatitude": null,
        "capitalLongitude": null,
        "isoNumeric": 86
      },
      {
        "countryName": "Reunion",
        "countryCode1": "RE",
        "countryCode2": "REU",
        "countryFlag": "RE.png",
        "capital": "",
        "currencyCode": "EUR",
        "currencyName": "Euro",
        "currencySymbol": "€",
        "capitalLatitude": null,
        "capitalLongitude": null,
        "isoNumeric": 638
      }];

**Comment by sagarjadhav968** [comment]
Please add  [dataReader]="'data'" in your tamexio-data-table html tag & change your data structure like...it works...
this.options = {
      "data": [{
        "countryName": "Myanmar",
        "countryCode1": "MM",
        "countryCode2": "MMR",
        "countryFlag": "MM.png"
        "capital": "",
        "currencyCode": "MMK",
        "currencyName": "Kyat",
        "currencySymbol": "K",
        "capitalLatitude": null,
        "capitalLongitude": null,
        "isoNumeric": 104
      }, {
        "countryName": "U.S. Virgin Island",
        "countryCode1": "VI",
        "countryCode2": "VIR",
        "countryFlag": "VI.png",
        "capital": "",
        "currencyCode": "USD",
        "currencyName": "Dollar",
        "currencySymbol": "$",
        "capitalLatitude": null,
        "capitalLongitude": null,
        "isoNumeric": 850
      }, {
        "countryName": "Latvia",
        "countryCode1": "LV",
        "countryCode2": "LVA",
        "countryFlag": "LV.png",
        "capital": "",
        "currencyCode": "LVL",
        "currencyName": "Lat",
        "currencySymbol": "Ls",
        "capitalLatitude": null,
        "capitalLongitude": null,
        "isoNumeric": 428
      }, {
        "countryName": "British Indian Ocean Teritory",
        "countryCode1": "IO",
        "countryCode2": "IOT",
        "countryFlag": "IO.png",
        "capital": "",
        "currencyCode": "USD",
        "currencyName": "Dollar",
        "currencySymbol": "$",
        "capitalLatitude": null,
        "capitalLongitude": null,
        "isoNumeric": 86
      }, {
        "countryName": "Reunion",
        "countryCode1": "RE",
        "countryCode2": "REU",
        "countryFlag": "RE.png",
        "capital": "",
        "currencyCode": "EUR",
        "currencyName": "Euro",
        "currencySymbol": "€",
        "capitalLatitude": null,
        "capitalLongitude": null,
        "isoNumeric": 638
      }]
    };

**Comment by pratikthecook** [comment]
Haved fixed the issue f35b83f3111d95ac9886098078f6616afb016b5e , you can now use your JSON with the existing structure. Update the package using
`npm install amexio-ng-extensions@latest`
