### ISSUE TITLE
Install Dependent Libraries does not work

### ISSUE THREAD

**Issue by yashjit** [meta-magic/amexio.github.io#34]
ERROR in Metadata version mismatch for module /amex.io/node_modules/amexio-ng-extensions/amexio-ng-extensions.d.ts, found version 4, expected 3, resolving symbol AppModule in /amex.io/src/app/app.module.ts, resolving symbol AppModule in /amex.io/src/app/app.module.ts

"dependencies": {
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "amexio-ng-extensions": "^3.2.2",
    "bootstrap": "^4.0.0-beta.2",
    "core-js": "^2.4.1",
    "font-awesome": "4.7.0",
    "jquery": "^3.2.1",
    "popper.js": "^1.12.9",
    "rxjs": "^5.4.2",
    "tether": "1.4.0",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.3.2",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.1.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }

please provide proper guideline to rectify dependencies issues, version conflicts etc.

**Comment by pratikthecook** [comment]
if you are using Angular Version < 5, then you need to install amexio version 3.0.11, as amexio 3.2+ supports only Angular 5+.
