### ISSUE TITLE
Radio Button does not works under ngx-admin hood as no value property provided.

### ISSUE THREAD

**Issue by yashjit** [meta-magic/amexio.github.io#36]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by sagarjadhav968** [comment]
Can u provide HTML tag of amexio radio which is you used..

**Comment by yashjit** [comment]
<amexio-radio-group [fieldLabel]="'Horizontal RadioGroup'" name ="gender"
              [fieldName]="'genderDemo'"
              [dataReader]="'response.data'"
              [displayField]="'gender'"
              [valueField]="'genderId'"
              [radioGroupBindData]="radioGroupData"
              (selectedValue)="setSelectedGender($event)"
              [column]="'6'">
</amexio-radio-group>

when i check the generated html in web debug there is now value property field in radio control so on submitting the form i am not getting any value from the radio button.

**Comment by sagarthecook** [comment]
@yashjit Please use an event which is setSelectedGender for getting all the selected values.
