### ISSUE TITLE
How to give my custome class applied on email input box place holder color and text color.

### ISSUE THREAD

**Issue by yashjit** [meta-magic/amexio.github.io#39]
<amexio-email-input 
[hasLabel]="false" 
name ="userEmail" 
(ngModel)="userEmail"
[placeholder]="'Email Id'"
[allowBlank]="false" 
[errorMsg] ="'Please enter Email Id. '"
[enablePopOver]="false"
[iconFeedBack]="true"
class="test" **----My Custom class**
 > </amexio-email-input>

My custom class does not applied to the input control which is email. test class load on span tag i.e feedback icon.

Is there any provision to place my custom style on input elements generated in amexio
<img width="852" alt="screen shot 2018-02-06 at 3 53 27 pm" src="https://user-images.githubusercontent.com/5338674/35854297-053cf014-0b56-11e8-9ddc-b7b06795117d.png">

**Comment by pratikthecook** [comment]
Try overriding the `input-control` from your app. For your reference : [CSS Class Definition Link ](https://github.com/meta-magic/amexio.github.io/blob/704e767b9fe3ba202b946b74d7f1a34661144aed/src/styles/default/componentstyles/input.scss#L31)
If your issue is resolved, please do Close it.
