### ISSUE TITLE
SA - Download Icon

### ISSUE THREAD

**Issue by arafkarsh** [meta-magic/amexio.github.io#4]
**Sender**: araf.karsh@metamagic.in
**Comment**: Download Icon image broken... 
[Open #4 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-1s6s/p/amexio-api-a0fddca1/4)
**Notes**:
 - (1) Download Icon

<a href='https://usersnappublic.s3.amazonaws.com/2017-07-17/06-38/81c7b304-4f63-4b29-b219-17dd05a632b2.png'>![SA - Download Icon](https://usersnappublic.s3.amazonaws.com/2017-07-17/06-38/ff517d93-fe7e-4d14-9ac6-24ab8e75342b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-07-17/06-38/81c7b304-4f63-4b29-b219-17dd05a632b2.png'>Download original image</a>

**Browser**: Chrome 59 (macOS Sierra)
**Referer**: [http://www.amexio.org/metamagic-showcase/index.html#/home](http://www.amexio.org/metamagic-showcase/index.html#/home)
**Screen size**: 1920 x 1200 **Browser size**: 1379 x 1036

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by pratikthecook** [comment]
Fixed
