### ISSUE TITLE
How to display selected in amexio-dropdown by matching Key of two rest end points?

### ISSUE THREAD

**Issue by abhinavsachdeva2701** [meta-magic/amexio.github.io#40]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x ] Support request
</code></pre>

## Expected behavior
While using amexio-dropdown, I want to display the selected value by matching the Key coming from Rest API. Rest API is returning data in format [ {key1: "", value1: ""}, {key2: "", value2: ""}], I want to match this Key which is for dropdown data with another key coming from another Rest API. What will be the selected property in amexio-dropdown?

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by sagarthecook** [comment]
@abhinavsachdeva2701 You need to write your own logic on onSingleSelect event of amexio dropdown...

**Comment by abhinavsachdeva2701** [comment]
My question is when drop-down is loaded how to show selected value which is
coming from rest API ?

**Comment by pratikthecook** [comment]
Dropdown now emits the entire row data i.e `{key1: "", value1: ""}`  from the `onSingleSelect` event,besides the `ngModel's value` which is selected.
704e767b9fe3ba202b946b74d7f1a34661144aed
