### ISSUE TITLE
SA - Media Video Player

### ISSUE THREAD

**Issue by arafkarsh** [meta-magic/amexio.github.io#41]
**Sender**: araf.karsh@metamagic.in
**Comment**: Video player internals must be based on HTML5 standards.
[Open #16 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-1s6s/p/amexio-api-a0fddca1/16)
**Notes**:
 - (1) Video player internals must be based on HTML5 Standards

<a href='https://usersnappublic.s3.amazonaws.com/2018-02-08/11-48/5b4c64a4-cd15-4a4a-b84d-a25b7d0de436.png'>![SA - Media Video Player](https://usersnappublic.s3.amazonaws.com/2018-02-08/11-48/074bcb5c-7f15-4e35-8f23-13743c808ee4.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-02-08/11-48/5b4c64a4-cd15-4a4a-b84d-a25b7d0de436.png'>Download original image</a>

**Browser**: Chrome 64 (Macintosh)
**Referer**: [http://amexio.org/test/api/v4/#/video-demo](http://amexio.org/test/api/v4/#/video-demo)
**Screen size**: 1680 x 1050 **Browser size**: 1335 x 920

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by pratikthecook** [comment]
Fixed
