### ISSUE TITLE
step box with box and icons   [active] flag has inversed logic

### ISSUE THREAD

**Issue by baminmru** [meta-magic/amexio.github.io#42]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

<amexio-step-block  [active]="true"...   -   user cannot click  "active" block

## Expected behavior

<amexio-step-block  [active]="true"...   -   user CAN click  "active" block

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via

http://www.amexio.org/showcaseapp/v4/index.html#/step-box-icon
change [active] flag to direct true or false

	<amexio-steps [block]="true" [icon]="true" (onClick)="stepBlockClick($event)">
			<amexio-step-block [label]="'User'" [active]="true" [icon]="'fa fa-user'"></amexio-step-block>
			<amexio-step-block [label]="'Shop'" [active]="true" [icon]="'fa fa-address-card'"></amexio-step-block>
			<amexio-step-block [label]="'Payment'" [active]="false" [icon]="'fa fa-shopping-cart'"></amexio-step-block>
			<amexio-step-block [label]="'Confirmation'" [active]="false" [icon]="'fa fa-cc-visa'"></amexio-step-block>
		</amexio-steps>

if Active =true  stepbox is not clickable.
 
## Environment

<pre><code>
Angular version: X.Y.Z

5

Browser:
- [XX ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ XX] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
8.4.0
- Platform:  
Windows

Others:

</code></pre>

**Comment by sagarthecook** [comment]
@baminmru We have fixed this issue in amexio version 4.0.7 Please checkout..

**Comment by baminmru** [comment]
Thank You. Please tell me where I can see actual source code of the demo application for Amexio V4?

**Comment by sagarthecook** [comment]
@baminmru  we will check and get back to you soon
