### ISSUE TITLE
Data grid single row select mode

### ISSUE THREAD

**Issue by baminmru** [meta-magic/amexio.github.io#43]
## I'm submitting a...

<pre><code>
[ X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

When I click a datagrid row, the highlight color is applied to the row.
But when I click on another row selection the color on the previous row does not change.

The highlight color is applied to only Odd lines.

## Expected behavior

DataGrid [enable-checkbox] ="false" , so I expect a single row selection in grid.

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via

verify demo app
http://www.amexio.org/showcaseapp/v4/index.html#/simple-grid

## What is the motivation / use case for changing the behavior?

Work in master-detail mode is impossible

## Environment

<pre><code>
Angular version: X.Y.Z

5.0.0

Browser:
- [ XX] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ XX] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
8.4.0

- Platform:  
WINDOWS

Others:

</code></pre>

**Comment by arafkarsh** [comment]
We are working on this issue. Will get back to you asap.

**Comment by DatsGawas** [comment]
we have fixed this issue you will get the update in 4.0.8 version.
