### ISSUE TITLE
Can't resolve 'slider.png' in amexio-ng-extensions\styles\css\at-md-blue.css

### ISSUE THREAD

**Issue by bhanukumar04** [meta-magic/amexio.github.io#44]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
Looks like the images are not relative to the path specified in the css file, i can see the respective images are in the image folder.
Can't resolve 'slider.png'  in  node_modules\amexio-ng-extensions\styles\css\at-md-blue.css:1175:20:
Can't resolve 'search-icon.png' amexio-ng-extensions\styles\css\at-md-blue.css:584:28:

## Expected behavior
Images should be present in the same folder as the css file or should point to the specific path in the css file.
I have copied images to the css folder to get rid of the error and after that  am seeing the below warining

WARNING in ./node_modules/raw-loader!./node_modules/postcss-loader/lib?{"ident":"embedded","sourceMap":true}!./node_modules/amexio-ng-extensions/styles/css/at-md-blue.css
(Emitted value instead of an instance of Error) autoprefixer: E:\Angular\myproject\node_modules\amexio-ng-extensions\styles\css\at-md-blue.css:2710:5: Can not find grid areas: north, east, center, west, south

## Environment

<pre><code>
Angular version: 5.2.0
Angular Cli : 1.7.0-rc.0 
amexio-ng-extensions: 4.0.6

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.4.0
- Platform:  Windows

**Comment by pratikthecook** [comment]
Fixed the missing file issue 96b0776d13c78b821f617343e52383c9c499d223. For now you could run the app by setting the    `"styles": [ "../node_modules/amexio-ng-extensions/styles/css/at-md-blue.scss" ]` &  `"defaults": {"styleExt": "scss" }`
in your .angular-cli.json.

**Comment by bhanukumar04** [comment]
sure, will do it.  when  is the next build planned to put in npm rep?

**Comment by ketan-gote** [comment]
Fix will be part of 4.0.8
