### ISSUE TITLE
dropdown [(ngModel)]= "variable" work only from dropdown to variable 

### ISSUE THREAD

**Issue by baminmru** [meta-magic/amexio.github.io#45]
## I'm submitting a...

<pre><code>
[ X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

data in dropdown control changed only when selection changed, and NOT changed when I change value of bound varible

## Expected behavior

Two-Way Data Binding

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)
1. Use this as a base:
https://amexio-v4-dropdown.stackblitz.io/#/dropdownbasic
2. add text-input to form:
`<amexio-row>
					<amexio-column size="12">
            <amexio-text-input [field-label]= "'Test code'" name ="my code"  
                    [place-holder] = "'Code'" 
                    [icon-feedback] = "true" [(ngModel)]="countryCode1" >
                    </amexio-text-input>
	</amexio-column>
				</amexio-row>`

3. try to change text at text-input . No reaction from DropDown.   

## What is the motivation / use case for changing the behavior?

Impossible to edit data records in edit form in CRUD scenario

## Environment

Angular version: 5.0.0

Browser:
- [XX ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [XX ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.0.4  
- Platform:  WINDOWS 

Others:

</code></pre>

**Comment by baminmru** [comment]
This work fine in Amexio 3.2.
And now  this bug is critical !  

Offer to make changes in the  dropdown.component.ts 
and copy lines 174...183   after line 280  ( in function set value)
and also to function writeValue.
I use dropdown in single select mode and  this changes is ok for me.

**Comment by arafkarsh** [comment]
We are working on this issue. Will get back to you asap.

**Comment by DatsGawas** [comment]
Hi @baminmru 
    we have fixed this issue you will get update in 4.0.8 version.
