### ISSUE TITLE
file upload  attribute [field-label] not work

### ISSUE THREAD

**Issue by baminmru** [meta-magic/amexio.github.io#46]
## I'm submitting a...

<pre><code>
[ х ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

 [field-label]="'Photo Upload'"  but on form  I see label: Choose File

## Expected behavior

Label set to string from [field-label] attribute

## Minimal reproduction of the problem with instructions
See 
http://www.amexio.org/showcaseapp/v4/index.html#/fileupload-demo

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [XX ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [XX ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.4.0
- Platform:   Windows 10

Others:

</code></pre>

**Comment by arafkarsh** [comment]
We are working on this issue. Will get back to you asap.

**Comment by sagarthecook** [comment]
This issue has been fixed and will be available on v4.0.8 97b4ffa590b6fd39eb29effda5e170945cc24761
