### ISSUE TITLE
dropdown control open list only on click to textinput, click on arrow icon dont work

### ISSUE THREAD

**Issue by baminmru** [meta-magic/amexio.github.io#48]
## I'm submitting a...

<pre><code>
[X ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

control open list only on click to textinput, click on arrow icon dont work

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## Environment

<pre><code>
Angular version: 5.0

Browser:
- [XX ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ XX] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.0.4
- Platform:   Windows 10

Others:

</code></pre>

**Comment by arafkarsh** [comment]
We are working on this issue. Will get back to you asap.

**Comment by DatsGawas** [comment]
@baminmru 
   we have fixed this issue you will get update in 4.0.8 version.
