### ISSUE TITLE
your v2 demo date/time picker need jq???

### ISSUE THREAD

**Issue by luyouxin84** [meta-magic/amexio.github.io#5]
hello,i new for ur lib.
when i use date/time picker, it have a error out and said it need jquery..

i want to sure ur lib need jq?

**Comment by ketan-gote** [comment]
Yes its dependent on jQuery. As our date/time picker is dependent on bootstrap-datepicker & bootstrap-timepicker which is dependent on jQuery.

**Comment by luyouxin84** [comment]
i import jq 3.xx ,but the date/time picker not work.
err msg : $(....).datapicker is not a function

**Comment by luyouxin84** [comment]
i try another elements,but still not working good.
err test : $('[data-toggle="popover"]').popover =>undefined
it s look like problem for query worry dom???

**Comment by luyouxin84** [comment]
i fix problem, i dont install jq neither bootstrap4
i load these files in index,now it work good...

but dude ,u should mark depencies lib by hightlight!

**Comment by pratikthecook** [comment]
Have u added bootstrap-datepicker and bootstrap-time picker packages? 
If not please npm install them and add the bootstrap-datepicker.js and bootstrap-timepicker.js to your app.

**Comment by pratikthecook** [comment]
Are you using Angular CLI, if so the js needed to be added to "scripts" in the angularcli.json .Simply installing wont work. 
Thankyou for your feedback. 
I am closing this issue.
