### ISSUE TITLE
Warning :  Can not find grid areas: north, east, center, west, south @ at-md-blue.css:3134:5

### ISSUE THREAD

**Issue by bhanukumar04** [meta-magic/amexio.github.io#53]
## I'm submitting a...

<pre><code>
[ X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
Using   "../node_modules/amexio-ng-extensions/styles/css/at-md-blue.css"  in angular-cli.json, build is successful but giving a warning as below:

WARNING in ./node_modules/raw-loader!./node_modules/postcss-loader/lib?{"ident":"embedded","sourceMap":true}!./node_modules/amexio-ng-extensions/styles/css/at-md-blue.css
(Emitted value instead of an instance of Error) autoprefixer: E:\Angular\sampleproject\node_modules\amexio-ng-extensions\styles\css\at-md-blue.css:3131:5: Can not find grid areas: north, east, center, west, south

## Expected behavior
Fixed should be in css file make sure it find the gird areas referred in css

## Environment

<pre><code>
Angular version: 5.2.0

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: node : 9.4.0
angular -cli  : 1.7.0-rc.0
- Platform:  Windows

**Comment by pratikthecook** [comment]
We will be removing these warnings in next release as it seems to be a issue while theming angular components, you can check out the issue on Angular CLI Repo [Issue](https://github.com/angular/angular-cli/issues/9502#issuecomment-363119819)

**Comment by bhanukumar04** [comment]
i have checked the latest release(4.0.10)  still issue exists, attached the project , do npm install and do **ng serve** it will show the warning message.
[AmexioWindowSample.zip](https://github.com/meta-magic/amexio.github.io/files/1793985/AmexioWindowSample.zip)
