### ISSUE TITLE
Need Sample for dynamically changing menu using navbar or ( and) sidebar

### ISSUE THREAD

**Issue by baminmru** [meta-magic/amexio.github.io#54]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X ] Documentation issue or request
[X ] Support request
</code></pre>

## Current behavior

In some scenario I need disable or hide some menu items.  Can you add sample whith dynamic menu in documentation.

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by DatsGawas** [comment]
Hi @baminmru 
 Currently we don't have disable functionality for sidenavbar but we have hide functionality.
 here is the [demo](https://stackblitz.com/edit/sidenav-demo)

**Comment by ketan-gote** [comment]
Closing issue.
