### ISSUE TITLE
Wrong toggle image size

### ISSUE THREAD

**Issue by baminmru** [meta-magic/amexio.github.io#55]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

In  http://www.amexio.org/showcaseapp/v4/index.html#/toggle-demo   width of toggle is OK.
But in live preview   https://amexio-v4-toggle.stackblitz.io/#/toggle-demo   width is too  small.
In my application I see toggle as on live preview.

## Expected behavior

Change size of toggle class to 60 px as it is in demo  sample/

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## Environment

<pre><code>
Angular version: 
![toggle](https://user-images.githubusercontent.com/16590085/36366356-d1c0b212-155e-11e8-9e09-4ab4cec2e16f.png)

5.0

Browser:
- [XX ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [XX ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.4.0
- Platform:  Windows 

Others:

</code></pre>

**Comment by pratikthecook** [comment]
Thanks for reporting. Fixed in 3cfa37f658e25fe8fb2d1a6ebc94d4c9c2b50806
