### ISSUE TITLE
Form level validation not working form.invalid or !form.valid to [disabled] etc are not seems to be working

### ISSUE THREAD

**Issue by yashjit** [meta-magic/amexio.github.io#56]
Various form validations (invalid,valid etc) missing or i need to know more about amexio.
ngSubmit submits the form while selecting a row in basic drop down.

**Comment by pratikthecook** [comment]
@yashjit can u please elaborate or demonstrate with your source ?

**Comment by yashjit** [comment]
My Form Given Below - If I submit, then no form validation available to stop submitting form. Even if I select the row from drop down it submitted the form. If I use Angular form controls and validate them then it works smoothly.
---------------------------------------------------------------------------------------------------------------

"<form id="dForm" name="dForm" (ngSubmit)="submitD()" #dForm="ngForm" autocomplete="off" novalidate>
                <div *ngIf="errorMessage" class="alert alert-danger text-left" role="alert">
                <span class="glyphicon glyphicon-ban-circle" aria-hidden="true">{{errorMessage}}</span>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <amexio-dropdown (ngModel)="type"
                        [placeholder]="'Select Driver Type'"
                        name="dtype"
                        [allowBlank]="false"
                        [errorMsg] ="'Select Driver type.'"
                        [data]="typeList"
                        [displayField]="'name'"
                        [valueField]="'name'"
                        [width]="'340px'"
                        (onSingleSelect)="getSingleVal($event)"
                        >
                        </amexio-dropdown>
                    </div>
                    <div class="col-sm-6">
                        <amexio-text-input [hasLabel]="false" name ="driver"
                        (ngModel)="driver"
                        [placeholder]="'Driver Name'"
                        [allowBlank]="false" 
                        [errorMsg] ="'Enter unique driver name eg. D-DEL-3428'"
                        [minLength]="6" 
                        [minErrorMsg]="'Minimum 6 char required'"
                        [maxLength]="30"
                        [iconFeedBack]="true"
                        [enablePopOver]="true" 
                        [popoverPlacement]="'bottom'">
                        </amexio-text-input>
                    </div>
                    
                </div>
                <div class="row">
                    <div class="col-sm-6" *ngIf="isParent">
                        <amexio-text-input [hasLabel]="false" id="cid" name ="macid" #cid="ngModel"
                        (ngModel)="cid"
                        [placeholder]="'CAR ID'"
                        [allowBlank]="false" 
                        [errorMsg] ="'Enter car id.'"
                        [maxLength]="30"
                        [iconFeedBack]="true"
                        [enablePopOver]="true" 
                        [popoverPlacement]="'bottom'">
                        </amexio-text-input>
                    </div>
                    <div class="col-sm-6" *ngIf="!isParent">
                            <amexio-text-input [hasLabel]="false" name ="address"
                            (ngModel)="address"
                            [placeholder]="'Address'"
                            [allowBlank]="false" 
                            [errorMsg] ="'Enter Address of driver'"
                            [iconFeedBack]="true"
                            [enablePopOver]="true" 
                            [popoverPlacement]="'bottom'">
                            </amexio-text-input>
                        </div>
                    <div class="col-sm-6" *ngIf="isParent">
                        <amexio-text-input [hasLabel]="false" name ="model"
                        (ngModel)="model"
                        [placeholder]="'Car Model'"
                        [allowBlank]="true" 
                        [errorMsg] ="'Enter Car model'"
                        [enablePopOver]="true" 
                        [popoverPlacement]="'bottom'">
                        </amexio-text-input>
                    </div>
                    
                </div>
                
                <div class="input-group" *ngIf="isParent"><strong>Network Access Details</strong></div>
                <div class="row" *ngIf="isParent">
                    <div class="col-sm-6">
                        <amexio-text-input [hasLabel]="false" name ="user"
                        (ngModel)="user"
                        [placeholder]="'User Id'"
                        [allowBlank]="false" 
                        [errorMsg] ="'Enter User of car'"
                        [iconFeedBack]="true"
                        [enablePopOver]="true" 
                        [popoverPlacement]="'bottom'">
                        </amexio-text-input>
                    </div>
                    <div class="col-sm-6">
                        <amexio-password-input [hasLabel]="false" id="password" name ="password" #password="ngModel"
                        (ngModel)="password"
                        [placeholder]="'Password'"
                        [allowBlank]="true" 
                        [errorMsg] ="'Enter user password.'"
                        [iconFeedBack]="true"
                        [enablePopOver]="true" 
                        [popoverPlacement]="'bottom'">
                        </amexio-password-input>
                    </div>
                        
                </div>
                <div class="row" *ngIf="isParent">
                    <div class="col-sm-6">
                        <amexio-text-input [hasLabel]="false" name ="address"
                        (ngModel)="address"
                        [placeholder]="'Address'"
                        [allowBlank]="false" 
                        [errorMsg] ="'Enter Address of user'"
                        [iconFeedBack]="true"
                        [enablePopOver]="true" 
                        [popoverPlacement]="'bottom'">
                        </amexio-text-input>
                    </div>
                    
                </div>
                
                <div class="input-group">
                <nb-checkbox name="enabled" [(ngModel)]="enabled" [required]>Activate</nb-checkbox>
                </div>
                
                <button type="submit" class="btn btn-primary" [disabled]="!dForm.valid">Submit</button>
</form>"

**Comment by pratikthecook** [comment]
Currently you would have to work with the Angular Form, as for the <form> tags, we would be supporting them in upcoming releases.

**Comment by sagarthecook** [comment]
Please refer [http://amexio.org/api/v4.1/index.html#/form-demo](url) this link for form validation.
