### ISSUE TITLE
Pagination component Onfirst click, page change event is not emitted.

### ISSUE THREAD

**Issue by bhanukumar04** [meta-magic/amexio.github.io#58]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
when you click on page last its working and emitting the page change event , but when you click on the go to first its not emitting the events.
 
see the  paginator.component.ts  code below:

onFirstClick() {
    this.activePageIndex = 0;
    this.changeRows(this.pageIndex[0], 0, null);
  }

  onLastClick() {
    this.activePageIndex = this.activePages.length - 1;
    this.changeRows(this.pageIndex[this.pageIndex.length - 1], this.pageIndex.length - 1, null);
    this.activePageIndex = this.activePages.length - 1;
    this.activePage = this.activePages[this.activePages.length - 1];
    this.onPageChange.emit(this.activePage);
  }

## Expected behavior
when you click on go to first it should emit event , for all other clicks its working expect go to first.

## Environment

<pre><code>
Angular version: 5.2.0
npm: 9.X

Browser:
- [ X] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ X] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ X] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.X
- Platform:   Linux

**Comment by pratikthecook** [comment]
Fixed 32de82626782e760c8a95fb04914265369ba25d5
