### ISSUE TITLE
dropdown not working

### ISSUE THREAD

**Issue by luyouxin84** [meta-magic/amexio.github.io#6]
err message：　ERROR Error: No provider for CommonHttpService!

．．．pls guys,check ur depency lib

**Comment by pratikthecook** [comment]
Can you please post your usage source code? Also have you injected `CommonHttpService` in any of your component?

**Comment by luyouxin84** [comment]
i dont inject CommonHttpService , there s detail for that object mention in your document..

i just copy ur html code in your document

**Comment by luyouxin84** [comment]
now i import CommonHttoService from amexio-ng-extensions , it may fix the issus.
but a new issus out.. 
error msg :   ReferenceError: Messenger is not defined..
it s look like u define 2 global variable in common.http.service.ts , $ and Messenger .i know $ is jq but what Messenger is?

**Comment by pratikthecook** [comment]
Please include the following JS and CSS in your app.The message to include this is displayed on the console. 
https://codeload.github.com/HubSpot/messenger/legacy.zip/master
We will update the docs accordingly, Thanks

**Comment by luyouxin84** [comment]
by the way, same problem is happen with radio and checkbox of input component

**Comment by pratikthecook** [comment]
Are you facing the problem after configuring it as mentioned above?

**Comment by luyouxin84** [comment]
before configuring messenger, after import messenger ,i wasn't have try

**Comment by pratikthecook** [comment]
[https://github.com/meta-magic/amexio.github.io/commit/1f8db2d4769d3069c300604e59dc50640e3470c4](url) 
Please Close the issue once its resolved.
