### ISSUE TITLE
time picker - manual input for hour / minute dont work

### ISSUE THREAD

**Issue by baminmru** [meta-magic/amexio.github.io#60]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

Manual input dont work in control.
I change minute to 00 manually  and send  data to server.
After refresh minutes set back to 22 ( for example).

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ X] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.4.0
- Platform:   Windows 10

Others:

</code></pre>

**Comment by pratikthecook** [comment]
Fixed 1f2e0d8ae568abf4fcfd7d9e8ac4f7c8ced80dfe
