### ISSUE TITLE
Is it possible to populate amexio dropdown without using http-url property?

### ISSUE THREAD

**Issue by abhinavsachdeva2701** [meta-magic/amexio.github.io#62]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ x] Support request
</code></pre>

## Current behavior
Right now, when I pass REST API Url in the amexio dropdown in http-url property, the dropdown populates with values.

## Expected behavior
Is it possible to populate dropdown without using http-url. What i want to do is define the REST API url in Angular Service and then i want to populate the values in dropdown.

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## What is the motivation / use case for changing the behavior?
I don't want to pass any rest url in HTML components.

## Environment

<pre><code>
Angular version: 4.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by sagarthecook** [comment]
@abhinavsachdeva2701 You can use data attribute for local data refer [Link](http://amexio.org/api/v4/index.html#/dropdownbasic)

**Comment by baminmru** [comment]
--- html ---

<amexio-dropdown 
	 [field-label]="'Only one answer'" name ="onlyOneAnswer" 
	 [(ngModel)]="onlyOneAnswer"
	 [display-field]="'name'"
	 [value-field]="'id'"
	 [data]="enumTriStateCombo()"
	 >
</amexio-dropdown>


--- typescript ---

export class ComboInfo{ 
	id:string; 
	name:string; 
} 


/* YesNo - No / Yes -> (0 / 1) */ 
public enumYesNoCombo(){
	return this.enumYesNo;
}
enumYesNo:Array<ComboInfo> =[

 {id:'1',name:'Yes'}
, {id:'0',name:'No'}	];

**Comment by DatsGawas** [comment]
Hi @baminmru [data] attribute takes input as Array or Object.
your code should be like this
<amexio-dropdown
[field-label]="'Only one answer'" name ="onlyOneAnswer"
[(ngModel)]="onlyOneAnswer"
[display-field]="'name'"
[value-field]="'id'"
[data]="enumYesNo"
></amexio-dropdown>

**Comment by baminmru** [comment]
[data]="enumYesNo()" 

enumYesNo  is function returning array, not property

**Comment by abhinavsachdeva2701** [comment]
Thanks Team, I was able to get it working !!
