### ISSUE TITLE
Dropdown scrollbar drag not working in IE11

### ISSUE THREAD

**Issue by abhinavsachdeva2701** [meta-magic/amexio.github.io#64]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
I have made dropdown scrollable by adding following property
.amexio-dropdown-menu{
                max-height: 500px;
                overflow: auto;
            }

Scrollbar appears but when i drag it, dropdown collapse

## Expected behavior
Scroll drag should work, it is not working in IE11 but it is working in chrome and IE edge.

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by abhinavsachdeva2701** [comment]
Hi Team, Here is the IE version which is getting used for our application. Can we please investigate. If it is not working then I will have to use simple dropdown instead of amexio dropdown and that is huge code change.
![image001](https://user-images.githubusercontent.com/16698964/37156170-5df67594-22b3-11e8-9688-759ab6018d53.png)

**Comment by ketan-gote** [comment]
@abhinavsachdeva2701 

We tested our demo app on IE11 and Edge, and dropdown is working. Can you let us which version of Amexio you are using. Also we can not made drop-down content drag-able.  

<img width="1596" alt="screen shot 2018-03-15 at 10 31 24 am" src="https://user-images.githubusercontent.com/23295769/37445173-418bb278-283c-11e8-999b-d43712c718a5.png">

**Comment by abhinavsachdeva2701** [comment]
It's IE 11 version 11.0.9600.18837, yes it's working in my laptop IE edge and IE 11, but in my office IE 11 version, it seems to not work, looks like when i make it open box instead of dropdown, the scrollbar works. For now have replaced with simple dropdown as go-live date is near by, but will continue to fix this soon. If you are able to replicate it and figure out, please let me know. Thanks.

**Comment by ketan-gote** [comment]
Closing this issue, as its working of IE11 and Edge. Also it looks specific problem on some office machine.
