### ISSUE TITLE
PROD Build gives error : Property 'auto' does not exist on type 'AmexioWindowPaneComponent'.

### ISSUE THREAD

**Issue by bhanukumar04** [meta-magic/amexio.github.io#65]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
when i do ng build --prod on the project it gives me the  error:  
**ERROR in node_modules\amexio-ng-extensions\amexio-ng-extensions.d.ts.AmexioWindowPaneComponent.html(4,36): : Property 'auto' does not exist on type 'AmexioWindowPaneComponent'.**

## Expected behavior
Prod build should not fail, should work as its working with **ng serve** command

## Minimal reproduction of the problem with instructions
Attached the project, do npm install and then we do  ng build --prod  build fails with error ---- ERROR in node_modules\amexio-ng-extensions\amexio-ng-extensions.d.ts.AmexioWindowPaneComponent.html(4,36): : Property 'auto' does not exist on type 'AmexioWindowPaneComponent'.

## Environment

<pre><code>
Angular version: 5.2.7

For Tooling issues:
- Node version: 9.4.0
- Platform: Windows 

[AmexioWindowSample.zip](https://github.com/meta-magic/amexio.github.io/files/1793951/AmexioWindowSample.zip)

**Comment by ketan-gote** [comment]
@bhanukumar04  - We will look into this asap, and release the patch for it.

**Comment by ketan-gote** [comment]
@bhanukumar04 - Issue has been fixed and pushed. Please use amexio-ng-extensions@4.0.11

**Comment by bhanukumar04** [comment]
Thank you, it was really very quick, Appreciate it!!  Now the prod build is passing , this can be closed.

**Comment by ketan-gote** [comment]
Closing Issue

**Comment by ketan-gote** [comment]
Closing
