### ISSUE TITLE
How to get amexio tab disabled based on a condition, is there any property on the tab?

### ISSUE THREAD

**Issue by abhinavsachdeva2701** [meta-magic/amexio.github.io#67]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ x] Support request
</code></pre>

## Current behavior

I am using amexio -tab (Horizontal) in my application

## Expected behavior
Based on certain condition, i.e. if type from REST API is coming as daily, i want to show daily tab and rest tabs should be disabled.

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by sagarthecook** [comment]
Tab disabled  property is not available in current version of Amexio.we will add this property in next versioned amexio.

**Comment by abhinavsachdeva2701** [comment]
Hi Team, there is a disable property already available to use in amexio 3.x version, I was able to get it working. Thanks. It could be enhancement in amexio current version, not sure.

**Comment by anaghak07** [comment]
feature to disable tab will be available in Amexio v 4.1.5 update

for more information visit http://amexio.org/api/v4.1/index.html#/basic-tab-demo
