### ISSUE TITLE
Data Grid - Group BY

### ISSUE THREAD

**Issue by yashjit** [meta-magic/amexio.github.io#68]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ x] Feature request
[ ] Documentation issue or request
[ x] Support request
</code></pre>

## Current behavior

DataGrid - Group By Feature -
Table Header columns are arranged in alphabetical order not the column name I want.

## Expected behavior

(Id, Company, Eval, Run, Transaction, Run Count, Framework) is expected behavior of column header but shows like
(Company, Eval,  Framework, ID, Run, Run count Transaction)
## Minimal reproduction of the problem with instructions

                            <amexio-data-table
                            [title]="'Stack up and Share'"
                            [pageSize] = "5"
                            [groupByColumn]="true"
                            [groupByColumnIndex]="'company'"
                            [dataReader]="'runs'"
                            [dataTableBindData]="draftView"
                            [checkboxSelect]="true"
                            (selectedRowData)="onRowSelect($event)"
                            (rowSelect)="onRowClick($event,'up')">
                            <amexio-data-table-column [dataIndex]="'id'" [dataType]="'number'" [hidden]="false" [text]="'ID'"></amexio-data-table-column>
                            <amexio-data-table-column [dataIndex]="'evaluator'" [dataType]="'string'" [hidden]="false" [text]="'Evaluator'"></amexio-data-table-column>
                            <amexio-data-table-column [dataIndex]="'company'" [dataType]="'string'" [hidden]="false" [text]="'Company'"></amexio-data-table-column>
                            <amexio-data-table-column [dataIndex]="'transactions'" [dataType]="'string'" [hidden]="false" [text]="'Transaction'"></amexio-data-table-column>
                            <amexio-data-table-column [dataIndex]="'run'" [dataType]="'number'" [hidden]="false" [text]="'Run'"></amexio-data-table-column>
                            <amexio-data-table-column [dataIndex]="'framework'" [dataType]="'string'" [hidden]="false" [text]="'Framework'"></amexio-data-table-column>
</amexio-data-table> 

 

## Environment

Angular version: 1.5+

Browser:
- [ x] Chrome (desktop) version XX
- [ x] Chrome (Android) version XX
- [ x] Chrome (iOS) version XX
- [ x] Firefox version XX
- [ x] Safari (desktop) version XX
- [ x] Safari (iOS) version XX
- [x ] IE version XX
- [ x] Edge version XX
 
For Tooling issues:
- Node version: XX  
8.9
- Platform:  
Angular 1.6
Others:

</code></pre>

**Comment by yashjit** [comment]
<img width="678" alt="screen shot 2018-03-15 at 9 12 48 am" src="https://user-images.githubusercontent.com/5338674/37443424-0f1faff6-2832-11e8-9920-d88b5072f6b1.png">

**Comment by DatsGawas** [comment]
Hi @yashjit The problem your facing that might be present in amexio version 3.0.x. Now we have updated our library in which we have fixed issue.
 so please use updated version :- current version is 4.1.5.
 [Here](https://stackblitz.com/edit/datagrid-groupby-sample) I have created sample app with groupby datagrid.
thanks.
