### ISSUE TITLE
SA - Hi,  can you please add stacked Bar chart. Curretly, you are proving the m[...]

### ISSUE THREAD

**Issue by arafkarsh** [meta-magic/amexio.github.io#69]
**Sender**: durgaprasad.madamsetti@gmail.com
**Comment**: Hi,

can you please add stacked Bar chart. Curretly, you are proving the multiple bars iwth different color. We need one bar should divided into the different colors.

Thanks & regards
Durga
[Open #19 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-1s6s/p/amexio-api-a0fddca1/19)

<a href='https://usersnappublic.s3.amazonaws.com/2018-03-21/11-04/7c606c6a-d8b4-4e47-b89c-553bd9beb75c.png'>![SA - Hi,  can you please add stacked Bar chart. Curretly, you are proving the m(...)](https://usersnappublic.s3.amazonaws.com/2018-03-21/11-04/3f1deee6-bc7b-48dd-bbd9-0ee8fdbde488.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-03-21/11-04/7c606c6a-d8b4-4e47-b89c-553bd9beb75c.png'>Download original image</a>

**Browser**: Chrome 65 (Windows 10)
**Referer**: [http://www.amexio.org/api/v4.1/index.html#/simple-grid](http://www.amexio.org/api/v4.1/index.html#/simple-grid)
**Screen size**: 1920 x 1080 **Browser size**: 1858 x 1014

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ketan-gote** [comment]
Bar chart has stacked bar option, we will send small example of stack bar implementation to you.

**Comment by sagarthecook** [comment]
Stacked Bar Chart example:[http://amexio.org/api/v4.1/index.html#/bar-chart-demo](url)

**Comment by ketan-gote** [comment]
Closing this issue.
