### ISSUE TITLE
SA - Bhanu

### ISSUE THREAD

**Issue by arafkarsh** [meta-magic/amexio.github.io#7]
**Sender**: bhanu.yandra@gmail.com
**Comment**: Demo not loading in IE or Chrome
[Open #5 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-1s6s/p/amexio-api-a0fddca1/5)
**Notes**:
 - (1) Not loading in chrome or IE

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-07/10-36/383d5aaa-5886-469c-b512-a43414ea6b86.png'>![SA - Bhanu](https://usersnappublic.s3.amazonaws.com/2017-08-07/10-36/0c8c4e19-65b8-456a-bc8d-dbededc86220.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-07/10-36/383d5aaa-5886-469c-b512-a43414ea6b86.png'>Download original image</a>

**Browser**: Microsoft Internet Explorer 11 (Windows 8.1)
**Referer**: [http://www.amexio.org/showcaseapp/v2/index.html](http://www.amexio.org/showcaseapp/v2/index.html)
**Screen size**: 1600 x 900 **Browser size**: 1538 x 786

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by pratikthecook** [comment]
Previously we didnt include the polyfills for older browser, Now fixed
