### ISSUE TITLE
LICENSE file is not present under node_modules\amexio-ng-extensions

### ISSUE THREAD

**Issue by bhanukumar04** [meta-magic/amexio.github.io#70]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
When using Angular CLI , if we are doing prod build if there is LICENSE  file under node module package, it will automatically added 3rdpartylicenses.txt file.

## Expected behavior
LICENSE   should be present in amexio package.

# Environment

<pre><code>
Angular version: 5.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.5
- Platform:  Windows

Others:

</code></pre>

**Comment by sagarthecook** [comment]
@bhanukumar04  can you elaborate this issue?

**Comment by sagarthecook** [comment]
@bhanukumar04  we have added license file inside amexio package.Please check and close this issue
