### ISSUE TITLE
reopen issue #42 for v4.1.3  step box with box and icons: cursor have inverse logic

### ISSUE THREAD

**Issue by baminmru** [meta-magic/amexio.github.io#73]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by sagarthecook** [comment]
@baminmru we will check and get back to you soon.

**Comment by anaghak07** [comment]
this issue is fixed and will be part of Amexio  v4.1.5

fixes applied for step-box coursor 
active : default , disabled : disabled , clickable : pointer

for more information visist  http://amexio.org/api/v4.1/index.html#/step-box

**Comment by sagarthecook** [comment]
@baminmru Please checkout step box example : [https://stackblitz.com/edit/amexio-v4-stepbox](url)

**Comment by baminmru** [comment]
In this sample cusror icons for **Step-box index** work OK,

but for **Step box** - cusror  has inversed logic.

On active button you show red cursor , on  non-active you show hand - cursor!

**Comment by ketan-gote** [comment]
@baminmru Step box function as below.

- Active step box is not clickable so it has red cursor 
- InActive stepbox are clickable so it has cursor with hand
