### ISSUE TITLE
amexio-nav-item *ngFor don't work  for top level items

### ISSUE THREAD

**Issue by baminmru** [meta-magic/amexio.github.io#74]
## I'm submitting a...

<pre><code>
[X ] Regression (a behavior that used to work and stopped working in a new release)
[  ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

<amexio-nav [title]="'1234'"
			[logo]="'assets/images/logos/logo.png'" 
			[enable-side-nav-position]="false">
  <amexio-nav-item position-left *ngFor="let topMenu of topMenuData" >
    [type]="'link'"
	[title]="topMenu.label"
	[icon]="topMenu.icon"
	(onNavItemClick)="onClick(topMenu.link)" 
  </amexio-nav-item> 
 
  </amexio-nav>

no menu items on screen

## Expected behavior

work ok in v 4.10
## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by sagarthecook** [comment]
@baminmru we have updated navbar component from v.4.1.3 
refer [http://amexio.org/api/v4.1/index.html#/navbar-demo](url)

**Comment by ketan-gote** [comment]
@baminmru - We have enhanced navbar with new features so it can have link, button, textfield, dropdown menus (with icon + text). Please check API demo section for navbar.

**Comment by sagarthecook** [comment]
Please check out new navbar changes and close this issue.
