### ISSUE TITLE
Form validation. How to check mandatory fields are filled on form  before process input data ?

### ISSUE THREAD

**Issue by baminmru** [meta-magic/amexio.github.io#75]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ X] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by sagarthecook** [comment]
@baminmru you need to add angular form validation.

**Comment by ketan-gote** [comment]
@baminmru - We are adding form component in upcoming release which should take care for form validation. Till this component is release you will required to use angular validation using form.

**Comment by baminmru** [comment]
I try to use FormGroup+FormControl, but when  I add FormControlName =  "name"  to Amexio Control HTML markup  TS Compiler generate  errors (value property not defined).

Please create working sample for  validation.

**Comment by anaghak07** [comment]
@baminmru amexio-form has been released in 4.1.8 (beta) plz take a look at its implementation in API docs at http://amexio.org/api/v4.1/#/form-demo

**Comment by sagarthecook** [comment]
@baminmru Please checkout [http://amexio.org/api/v4.1/index.html#/form-demo](url) for form validation
