### ISSUE TITLE
DropDown control.  Display text always emtpty if bound value = 0

### ISSUE THREAD

**Issue by baminmru** [meta-magic/amexio.github.io#77]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

I have enum with  values   0 -X  1 - Y 2 -Z
I use DropDown to show data on form   
if var value 1 or 2 i see Y or Z,  if var value=0 DropDown text steel empty

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.0.4
- Platform:   Windows 
See my changes on dropdown component:

[dropdown.component.txt](https://github.com/meta-magic/amexio.github.io/files/1888877/dropdown.component.txt)

Others:

</code></pre>

**Comment by sagarthecook** [comment]
@baminmru are you using ENUM? can you elaborate this issue?
Please  check out attached example [https://stackblitz.com/edit/amexio-dropdown-control](url)

**Comment by baminmru** [comment]
I use array as data source, and integer as bound value
` <amexio-dropdown 
	 [field-label]="'On-line  тест'" name ="onlineTest" 
                    [place-holder]="'On-line  тест'" 
	 [(ngModel)]="currentVariantDescr.onlineTest"
            [allow-blank]="false" [error-msg] ="'Не задано: On-line  тест'" 
	 [display-field]="'name'"
	 [value-field]="'id'"
	 [data]="AppService.enumYesNoCombo()"
	 >

/* YesNo - Да / Нет (0 или 1) */ 
	public enumYesNoCombo(){
		return this.enumYesNo;
	}
	enumYesNo:Array<ComboInfo> =[

	 {id:'1',name:'Да'}
	, {id:'0',name:'Нет'}	];

`

**Comment by baminmru** [comment]
Change  your code, and and see a bug.
`import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent  {
localData:any;
model:Model;
constructor(){
this.localData=[{
  "name":"X",
  "value":"0"
},{
  "name":"Y",
  "value":"1"
},{
  "name":"Z",
  "value":"2"
}];
this.model=new Model();

}
}
export class Model{
  value:any;
  constructor(){
    this.value=0;  // 0 !='0' 
  }
}`

**Comment by sagarthecook** [comment]
@baminmru  will check and get back to you soon.

**Comment by sagarthecook** [comment]
@baminmru we have fixed this issue on c7d186101b7f5d1a2b34513d4b137fe49a413561 .
you will get the new changes on upcoming amexio release..

**Comment by sagarthecook** [comment]
We have fixed this issue on Amexio v4.1.6

**Comment by sagarthecook** [comment]
@baminmru  Please check out attached example of dropdown :[https://stackblitz.com/edit/amexio-dropdown-control](url) and close the issue
