### ISSUE TITLE
Negative Page Numbers in paging control

### ISSUE THREAD

**Issue by baminmru** [meta-magic/amexio.github.io#78]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

![pagingerror](https://user-images.githubusercontent.com/16590085/38538207-5b98fb76-3c9b-11e8-836c-ca59a90134a7.png)
Negative page Numbers, when press '<<' button

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ X ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  Windows

Others:

</code></pre>

**Comment by DatsGawas** [comment]
@baminmru this issue getting because your putting "rows" value greater than "pages" value.
for ex. <amexio-paginator [pages]="5" [rows]="20"></amexio-paginator>
above example will having issue.
 <amexio-paginator [pages]="20" [rows]="5"></amexio-paginator>
this will work fine.
**rows  should be less than pages**.
 I have put validation for that will get update in next release.
thanks

**Comment by baminmru** [comment]
This is  grid setup in my component:
` <amexio-datagrid 
		  [title]="'Вариант теста::Описание'" 
		  [page-size] = "10" 
		  [enable-data-filter]="false" 
		  [enable-checkbox]="false" 
		  [data]="VariantDescrArray" 
		  (selectedRowData)="onSelect($event)" 
		  (rowSelect)="onSelect($event)"> 
		  <amexio-data-table-column [data-index]="'baseTest_name'" [data-type]="'string'" [hidden]="false" [text]="'Базовый тест'"></amexio-data-table-column> 
		  <amexio-data-table-column [data-index]="'onlineTest_name'" [data-type]="'string'" [hidden]="false" [text]="'On-line  тест'"></amexio-data-table-column> 
		  <amexio-data-table-column [data-index]="'isPublic_name'" [data-type]="'string'" [hidden]="false" [text]="'Публичный вариант'"></amexio-data-table-column> 
		  <amexio-data-table-column [data-index]="'variantNum'" [data-type]="'string'" [hidden]="false" [text]="'Номер варианта'"> 
 		  <ng-template #amexioBodyTmpl let-column let-row="row">
             {{  ((row.variantNum) ? ((row.variantNum.length>100) ? row.variantNum.substr(0,100)+'...' : row.variantNum ) : '-') | removehtmltag }} 
           </ng-template>
		  </amexio-data-table-column> 
		  <amexio-data-table-column [data-index]="'theORG_name'" [data-type]="'string'" [hidden]="false" [text]="'Организация владелец'"></amexio-data-table-column> 
		</amexio-datagrid>   `
I  do not setup paginator  section.

**Comment by DatsGawas** [comment]
I will check and get back to you.

**Comment by DatsGawas** [comment]
Hi @baminmru using your datagrid template I have create sample app [https://stackblitz.com/edit/datagrid-sample-ui](https://stackblitz.com/edit/datagrid-sample-ui) but I am not able to find any issue in pagination.
Please go through it and try to create your scenario. If you found issue let me know.

**Comment by sagarjadhav968** [comment]
@baminmru  we have resolved above issue and available on amexio v4.1.6

**Comment by ketan-gote** [comment]
@baminmru do we need to more investigation, if note close the issue.
