### ISSUE TITLE
Text Area - Disable Color

### ISSUE THREAD

**Issue by rashmithakkar** [meta-magic/amexio.github.io#79]
![screenshot from 2018-04-09 19-50-44](https://user-images.githubusercontent.com/31242664/38539893-93e854b0-3cb7-11e8-9f8d-8b867d35d7d9.png)

When Text Area is disabled- color differs .. its not same as text field disable

**Comment by anaghak07** [comment]
@rashmithakkar committed the fix.. plz chk

**Comment by ketan-gote** [comment]
Closing this issue as its fixed.
