### ISSUE TITLE
amexio-dropdown has-label Properties useless

### ISSUE THREAD

**Issue by lc448986375** [meta-magic/amexio.github.io#81]
## I'm submitting a amexio-dropdown has-label properties useless

the source code of  amexio-dropdown 
`
<label [style.font-style]="fontstyle" [style.font-family]="fontfamily" [style.font-size]="fontsize">
        {{fieldlabel}}
</label>
`
not used the has-label property

**Comment by anaghak07** [comment]
fixed dropdown for has-label attribute

**Comment by ketan-gote** [comment]
Closing this issue as its fixed.
