### ISSUE TITLE
4.1.10 Runtime  error at TabView Control:    Cannot read property 'checkActionComponent' of undefined

### ISSUE THREAD

**Issue by baminmru** [meta-magic/amexio.github.io#83]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

ERROR TypeError: Cannot read property 'checkActionComponent' of undefined
    at AmexioTabComponent.ngAfterContentInit (amexio-ng-extensions.es5.js:18957)

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by DatsGawas** [comment]
Hi @baminmru 
  we are not able to reproduce above error in  version 4.1.10. Can you send me your TabView usage.

**Comment by baminmru** [comment]
Component in archive

[TestVariant.zip](https://github.com/meta-magic/amexio.github.io/files/2000298/TestVariant.zip)
