### ISSUE TITLE
Overlap grid column data when change browser  window size or zoom.

### ISSUE THREAD

**Issue by baminmru** [meta-magic/amexio.github.io#85]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

Content of column overlaps when browser window size changed.

## Expected behavior

![overlap](https://user-images.githubusercontent.com/16590085/40732080-300aed3a-643b-11e8-91f8-32e8292f0579.png)

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [ X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ X] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Allu123** [comment]
Any update on this issue?, since i'm also facing same issue on my data grid table.

**Comment by DatsGawas** [comment]
we have fixed this issue. You will get update in next point release.
