### ISSUE TITLE
amexio V4.2.2 Error on production build

### ISSUE THREAD

**Issue by baminmru** [meta-magic/amexio.github.io#86]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

Error on compiling:
node_modules/amexio-ng-extensions/amexio-ng-extensions.d.ts.ɵbr.html(13,49): Expected 1 arguments, but got 0.

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by sagarthecook** [comment]
@baminmru will check and get back to you soon

**Comment by sagarthecook** [comment]
@baminmru we have fixed this issue in v4.2.3 Please take an update of amexio
