### ISSUE TITLE
Tree Data grid

### ISSUE THREAD

**Issue by surajjadhav720** [meta-magic/amexio.github.io#87]
Tree Data grid -node click not fire.
is their any method  to get leaf node data not parent node

**Comment by DatsGawas** [comment]
Hi @surajjadhav720 will check and let you know.

**Comment by DatsGawas** [comment]
Hi @surajjadhav720 we have fixed issue. we have added "rowSelect" event for TreeDataGrid. this will be available from v4.2.6.
