### ISSUE TITLE
SA - Help regarding linking different zones of pie chart

### ISSUE THREAD

**Issue by arafkarsh** [meta-magic/amexio.github.io#89]
**Sender**: rpathak1518@gmail.com
**Comment**: Can I please know  how to add a router in different zones of pie chart?I need to link different zones to another page.

[Open #20 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-1s6s/p/amexio-api-a0fddca1/20)
**Notes**:
 - (1) Can I please know  how to add a router in different zones of pie chart?I need to link different zones to another page.

<a href='https://usersnappublic.s3.amazonaws.com/2018-07-06/10-08/3d4a3965-c0d0-46bc-bca3-ca16c36d5e4a.png'>![SA - Help regarding linking different zones of pie chart](https://usersnappublic.s3.amazonaws.com/2018-07-06/10-08/f8fbfa5b-0e0c-404c-8136-ac1482705056.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-07-06/10-08/3d4a3965-c0d0-46bc-bca3-ca16c36d5e4a.png'>Download original image</a>

**Browser**: Chrome 67 (Windows 7)
**Referer**: [https://amexio.org/api/v4.1/index.html#/pie-chart-demo](https://amexio.org/api/v4.1/index.html#/pie-chart-demo)
**Screen size**: 1600 x 900 **Browser size**: 1600 x 794

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by rashmithakkar** [comment]
Instead of google charts, we can suggest you to use d3 charts, where you will get click event and data of particular section, so that accordingly routing or any operations can be performed.
Refer [example](https://api.amexio.org/api/v5.15/index.html#/D3chart/amexio-d3-chart-pie).

Thanks.
