### ISSUE TITLE
Where do I place the <router-outlet> when I implement top and left nav bar.

### ISSUE THREAD

**Issue by alrajp** [meta-magic/amexio.github.io#91]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by sagarthecook** [comment]
@alrajp  Please check out below URL for side navbar with router-outlet 
URL-[ https://amexio-v4-side-nav-bar-l9wjaa.stackblitz.io/#/email](url)

**Comment by alrajp** [comment]
Thanks you so much.. Please find the code base where I placed the router-outlet, which is not displayed as im expecting...

which is overlapping from topnav main menu..

Unable to attache the screen short as there is no option to attach it.


'<amexio-nav
  [enable-side-nav-position]="false"
  [title]="'Amexio'"
  >
            <amexio-nav-item position-right
                                      [type]="'link'"
                                      [title]="'Amexio'"
                                      (onNavItemClick)="homeLink('http://amexio.tech')">
            </amexio-nav-item>
            <amexio-nav-item position-right
                                      [type]="'textfield'"
                                      [title]="'Enter your name'" [(ngModel)] = "uname">
            </amexio-nav-item>
            <amexio-nav-item position-right
                                      (onNavItemClick)="onClick('http://amexio.tech')"
                                      [icon]="'fa fa-bell fa-fw fa-lg'"
                                      [type]="'button'"
                                      style="cursor: pointer;">
            </amexio-nav-item>
            <amexio-nav-item position-right
                           [title]="'Settings'"
                           [type]="'menucontainer'">
                    <amexio-box background-color="purple" padding="true">
                      <amexio-label size="small-bold">This account is managed by metamagic.in. </amexio-label>
                    </amexio-box>
                      <amexio-row>
                        <amexio-column size="5">
                          <amexio-image [height]="'89.75px'" [width]="'89.75px'"  [c-class]="'image-round'">
                          </amexio-image>
                        </amexio-column>
                        <amexio-column size="7">
                          <amexio-label > John Deo </amexio-label>
                          <amexio-label > At Paris. </amexio-label>
                        </amexio-column>
                      </amexio-row>
                    <amexio-drop-down-menu-item
                                      [label]="'Settings'"
                                      [icon]="'fa fa-cog'"
                                      [separator]="true"
                                      (onClick)="onDropDownMenuClick($event)">
                    [</amexio-drop-down-menu-item>](url)
                    <amexio-drop-down-menu-item
                                      [label]="'Help Center'"
                                      [icon]="'fa fa-question-circle'"
                                      [separator] ="true"
                                      (onClick)="onDropDownMenuClick($event)">
                    </amexio-drop-down-menu-item>
                    <amexio-drop-down-menu-item>
                      <amexio-button
                                      [label]="'My Account'"
                                      [type]="'theme-color'"
                                      [tooltip]="'My Account'">
                      </amexio-button>
                    </amexio-drop-down-menu-item>
            </amexio-nav-item>
            <amexio-nav-item position-right *ngFor="let menus of topMenuData"
                              [type]="'menu'"
                              [title]="menus.text"
                              [data]="menus.submenus"
                              (onNavItemClick)="externalLink($event)">
            </amexio-nav-item>
</amexio-nav>

<router-outlet></router-outlet>

<br>
<amexio-side-nav
  [http-url]="'../assets/data/componentdata/sidenav.json'"
  [http-method]="'get'"
  [data-reader]="'data'"
  [width]="'275px'"
  [position]="'relative'">

</amexio-side-nav>'


Could it possible to share your code base. which helps me to understand easily?

**Comment by sagarthecook** [comment]
Hi, @alrajp 
Please add `<div style="padding-top: 68px;"><router-outlet ></router-outlet></div>` instead of `<router-outlet ></router-outlet>`

**Comment by sagarthecook** [comment]
@alrajp can you close this issue.

**Comment by ketan-gote** [comment]
Closing this issues
