### ISSUE TITLE
API docs site don't work

### ISSUE THREAD

**Issue by baminmru** [meta-magic/amexio.github.io#92]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://stackblitz.com/fork/angular or similar (you can use Our Amexio Sandbox On Stackbliz as a starting point: https://stackblitz.com/edit/amexio-sandbox)

## Environment

<pre><code>
Angular version: X.Y.Z <br>
Amexio version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ketan-gote** [comment]
@baminmru - Are you still facing same issue, as we are able to access.

**Comment by baminmru** [comment]
Try to open: https://amexio.org/api/v5.0/index.html  in Edge
I see only progress indicator and feedback window.
error in console:
 SCRIPT1009: SCRIPT1009: Expected '}'  at  vendor.885c547ab6a05c85fcc6.js (34011,4)

in IE, I receive  Security error.
In Chrome  it's look like network problem  some files failed to load.

**Comment by baminmru** [comment]
![default](https://user-images.githubusercontent.com/16590085/42767970-f85b5620-8926-11e8-8bc9-8f690c0e0cda.png)

Firefox network log. Same as Chrome. Files from amexio.org failed to load.

**Comment by deepali-arvind** [comment]
@baminmru thanks for detail logs 

we are investigating this issue , will update asap

**Comment by ketan-gote** [comment]
Closing this issue
