### ISSUE TITLE
getting exception 'nav-dropdown-content-right: undefined' 

### ISSUE THREAD

**Issue by Allu123** [meta-magic/amexio.github.io#95]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Expected behavior

<img width="1432" alt="screen shot 2018-08-04 at 5 43 44 pm" src="https://user-images.githubusercontent.com/17191466/43681031-0e1e2a78-980e-11e8-8314-c11f9f0c59a4.png">

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use Our Amexio Plunker as a starting point: http://plnkr.co/edit/M9AeGH?p=info)

## Environment

<pre><code>
Angular version: 6.1.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [X ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

    <div class="topnavmainbarinneritems"   // this line has some issues while rendering the page as mentioned in the screen short.
    [ngClass]="{'topnavmainbarinneritems-mobile':mobilemode,
     'nav-dropdown-content-right':enablerightclass}" >
        <amexio-nav-action *ngIf="isAction" [type]="type" [title]="title" [icon]="icon" (navLinkClick)="navItemClick($event)"></amexio-nav-action>
        <amexio-nav-textfield *ngIf="isTextField" [(ngModel)]="value"  [title]="title"></amexio-nav-textfield>
        <amexio-nav-menu *ngIf="isMenu" [title]="title" [icon]="icon" [data]="data"  (navLinkClick)="navItemClick($event)">
        </amexio-nav-menu>
        <amexio-nav-menu *ngIf="isMenuContainer" [title]="title" [icon]="icon" [type]="type" (navLinkClick)="navItemClick($event)">
            <ng-content></ng-content>
        </amexio-nav-menu>
    </div>

**Comment by sagarthecook** [comment]
We will check and get back to you soon..

**Comment by sagarthecook** [comment]
@Allu123 we have fixed this issue in v5.0 version. if you run into any more issues let us know so will fix ASAP.
