### ISSUE TITLE
SA - Side Nav Bar issue

### ISSUE THREAD

**Issue by arafkarsh** [meta-magic/amexio.github.io#96]
**Sender**: araf.karsh@metamagic.in
**Comment**: Side Nav Bar Down Arrow alignment issue
[Open #22 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-1s6s/p/amexio-api-a0fddca1/22)
**Notes**:
 - (1) Down Arrow Alignment issue

<a href='https://usersnappublic.s3.amazonaws.com/2018-08-07/15-17/db64d564-5aef-498c-a5b3-7a6c1cd78107.png'>![SA - Side Nav Bar issue](https://usersnappublic.s3.amazonaws.com/2018-08-07/15-17/90e7eff1-2e6e-4f92-b355-b0e9f4b47942.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-08-07/15-17/db64d564-5aef-498c-a5b3-7a6c1cd78107.png'>Download original image</a>

**Browser**: Firefox 61 (Macintosh)
**Referer**: [https://amexio.org/api/v5.1/index.html#/getting-started](https://amexio.org/api/v5.1/index.html#/getting-started)
**Screen size**: 1680 x 1050 **Browser size**: 1215 x 884

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ketan-gote** [comment]
Fixed.
